### ISSUE TITLE
Generic Queue Interface

### ISSUE THREAD

**Issue by lonnieezell** [codeigniter4/CodeIgniter4#117]
Provides a common interface to queueing tasks, including to formal queue engines like RabbitMQ or Beanstalkd, and a simple file and database for local versions. Useful for off-loading time-consuming tasks like sending emails, push notifications, image processing, etc.

Handlers: 
- [ ] RabbitMQ
- [ ] Local File
- [ ] Local Database
- [ ] Redis
- [ ] Memcached

Integrations: 
- [ ] Email 
- [ ] Events

**Comment by noldor** [comment]
I wrote functions I think the queue interface should have. Could you check it?

----
Queue
=====

overview
--------

This queue interface will be aware of RabbitMQ. There are 4 components.

 - Provider
 - Exchanger
 - Queue
 - Consumer

There are multiple Consumers listening to same Queue, however, each message is processed by just one Consumer. It will not process twice.

If error raise, message will get back to same queue and will be retried. Retry count is limited. If retry count is over, the message will be deleted.

retry delay
-----------

Sometimes, Consumer job fails repeatedly (e.g. when the mail server is temporary unavailable, etc...).
So we should retry with delay.
Delay time can be modified in the config file.

retry count limit
-----------------

When a job that always fails retry forever, the queue is full of such jobs.
So a job should be restricted the number of retrying.
Retry limit can be modified in the config file.

Retry count is passed to the callback function.

rejecting a job by Consumer
---------------------------

When a error arises, job will be retried automatically. Also we can retry a job manually.
If a specific exception is thrown, then this queue system will retry as failure.

endless loop on Consumer's job
------------------------------

When a job fall into a endless loop, it seems that the job is processing forever from the point of view of the Queue. The job will be neither success nor failure.
This queue system doesn't take care of it. A programmer should set `max_execution_time` or `set_time_limit()` properly.

On the Database Handler nobody can decide whether a job is processing or not, so the handler regards a job taking more than 300 sec as failure and retry it.

return without waiting after fetching a message
------------------------------------------------

Normally, a request via a browser should response ASAP. So `fetch()` returns right away whether there are messages or not.
`fetch()` work with a single message.

waiting when there are no messages
-----------------------------------

If a job works as background job, the job should wait for a messages when there are no messages.
Because starting PHP process require CPU power.

`receive()` is the same as `fetch()`, except it will wait if there are no messages.
`receive()` work with a single messages and we should not call it repeatly with endless loop like `while(1)`. PHP process will kill itself by `max_execution_time`. We should use `supervisor`, `daemontools`, `systemd` or the like. At worst, `crond` (on cheap hosting services).


----
Thank you for taking time.

**Comment by kenjis** [comment]
@michalsn published "CodeIgniter Queue".
https://michalsn.github.io/codeigniter-queue/

**Comment by kenjis** [comment]
@lonnieezell Can we close this?

**Comment by lonnieezell** [comment]
Yep I believe so.

**Comment by lonnieezell** [comment]
Though I can't seem to do that from mobile.

**Comment by kenjis** [comment]
See https://github.com/codeigniter4/queue
