### ISSUE TITLE
Kint problem, chinese characters

### ISSUE THREAD

**Issue by Przem4S** [codeigniter4/CodeIgniter4#1177]
Hi, I have problem with somethink that:
![chenese](https://user-images.githubusercontent.com/37654401/44547231-b99f1900-a71a-11e8-823a-809095129da4.PNG)

I found problem with Kint: system/ThirdParty/Kint.php

When clean out eval all works fine but whitout Kint?
Server: Debian Jessie, PHP: 7.1.20

**Comment by lonnieezell** [comment]
You're going to have to explain things a little more because I don't have a clue what you were trying to do when this happened, how to recreate it, or even really what you're talking about. Sorry. 

Plus - might be out of luck here - because Kint is a third-party piece of code that we can't make local modifications to.

**Comment by Przem4S** [comment]
@lonnieezell This happend on clean installation of CI4. Mayby I don't have some library (for Kint?), but now, only remove eval from this file resolve problem.

**Comment by lonnieezell** [comment]
@Przem4S can you describe your setup? And what were you trying to output? Specific instructions to recreate are required.
