### ISSUE TITLE
TODO BaseConnection needs better error handling

### ISSUE THREAD

**Issue by jim-parry** [codeigniter4/CodeIgniter4#1254]
Database/BaseCOnnection::query(...) has a todo note...
deal with errors (they are currently ignored)

**Comment by jim-parry** [comment]
@lonnieezell Cleaning up todo tags :-/

**Comment by lonnieezell** [comment]
I saw that! Though in this case you were a bit pre-mature. You just returned instead of handling the error. I need to look back at the original driver, but I believe the intent was to capture any errors that happened during a transaction and display them to the user (depending on CI_DEBUG setting?) after the transaction has been closed.
