### ISSUE TITLE
TODO Database utility backup builder

### ISSUE THREAD

**Issue by jim-parry** [codeigniter4/CodeIgniter4#1257]
Database/SQLite3/Utils::_backup() has a todo note...
build

**Comment by jim-parry** [comment]
None of the handlers implements a backup. Dropping this as a todo!

**Comment by lonnieezell** [comment]
Well - that begs the question: are we going to include a backup builder, like CI3 has, into any of the drivers? If so, it was only MySQL that had it previously. My plan was to try to refactor the original into one that used file streaming to get around the size constraints it had previously.

I'm not 100% sure a backup method is needed since they each have ways in the ecosystem to do that (like mysqldump). If we're not, though, we need to make sure it's not in the user guide anywhere.

**Comment by MGatner** [comment]
At this point there are not plans to support database backups through the framework.

**Comment by MGatner** [comment]
See also: https://forum.codeigniter.com/thread-72750-page-4.html
