### ISSUE TITLE
Unable set ENVIRONMENT with Spark

### ISSUE THREAD

**Issue by uno-de-piera** [codeigniter4/CodeIgniter4#1268]
The [documentation](https://bcit-ci.github.io/CodeIgniter4/general/environments.html) says that for change the environment we have some options:

```
Set CI_ENVIRONMENT=<environment> from .env file
Use SetEnv CI_ENVIRONMENT <environment> from .htaccess file on Apache
```

I tried all options but I'm unable to change the environment on my application.

The issue appears with spark server, if I serve my application with php -S localhost:<port> -t=public all works fine.

**Comment by lonnieezell** [comment]
Does not appear to be a bug. If I set it in .env file it works just fine. Tested by `dd(ENVIRONMENT)`  within the spark file itself. Changes appeared as expected.

**Comment by truelineinfotech** [comment]
@uno-de-piera  you are right.  @lonnieezell  i am facing same issue. 
**CI_ENVIRONMENT variable value is not changing**
if i set CI_ENVIRONMENT=production in .env file then Debug Toolbar is still displayed and CI_ENVIRONMENT variable value is not changing.

because of `$_SERVER['CI_ENVIRONMENT'] = 'development';` defined in rewrite. php
it is replacing CI_ENVIRONMENT variable value and  if you remove above line in rewrite.php file then it will work.

file path : `appstarter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php`
Line : 20

**CodeIgniter 4 version**
4.0.0-beta.2
**Context**
	OS : windows 8.1
	webserver : apache2.4
	php version : 7.2

**Comment by truelineinfotech** [comment]
**screenshot**
https://pasteboard.co/I94mF2d.jpg

**Comment by truelineinfotech** [comment]
@lonnieezell  you can close this issue.
