### ISSUE TITLE
Lack of proper instruction in documentation for changing Application and System folder name

### ISSUE THREAD

**Issue by webdevron** [codeigniter4/CodeIgniter4#1366]
---
name: Bug report
about: Application and System folder name change

---

**Describe the bug**
According to the doc, to change the **Application** and **System** folder name we should change the `$systemDirectory` and `$applicationDirectory` in **application/Config/Path.php**.

Actually this is not enough. Along with the we have to change this two variables in **index.php** file, `$pathsPath = FCPATH . '../application/Config/Paths.php';` and `$app = require FCPATH . '../system/bootstrap.php';` as they are containing the folders name.

**CodeIgniter 4 version**
Version 4.0.0-alpha.2

**Context**
 - OS: Windows 10
 - Web server Apache/2.4.35 (Win32) OpenSSL/1.1.0i
 - PHP 7.2.11

**Comment by jim-parry** [comment]
This will be addressed with the repo reorg.

**Comment by BadeelProject** [comment]
also a pretty change would be better on : 
file : system\Config\Services::render() : L487
move up the logic check of 
`		if (is_null($viewPath))
		{
			$paths = config('Paths');

			$viewPath = $paths->viewDirectory;
		}`
as the first operation to check in order to avoid getting error if the application/Views is moved out or renamed.
also , the changing of viewsDirectory must verify the absolute location of the folder, cause now if the Views is moved to the root path, it won"t work untill adding the parent location two dots "../views"
