### ISSUE TITLE
ErrorException  Trying to get property 'affected_rows' of non-object 

### ISSUE THREAD

**Issue by nowackipawel** [codeigniter4/CodeIgniter4#1559]
![screenshot_2018-11-30_18-29-52](https://user-images.githubusercontent.com/8414802/49305183-d80d7100-f4ce-11e8-9109-1a993ec7f332.png)

Not sure why this is happening. 
Normal update action in  one of the models method: 
`$this->update($id, ['column' => $value])`
and then:
`return $this->db->affectedRows()` is causing this exception.

**Comment by nowackipawel** [comment]
Ok it was because of validation rules. 
I've got validation rules for every fields in my model, and I am updating only one field and.... there were errors in this operation.
However:
* shouldn't affectedRows metod return 0 instead of exception?
* shouldn't validation library check only fields which are updating?

**Comment by natanfelles** [comment]
@nowackipawel 

- shouldn't affectedRows metod return 0 instead of exception?

It should not throw an exception. It seems that there is still no connection to the database when the `affectedRows()` method is called.

 - shouldn't validation library check only fields which are updating?

I think no, because if you set rules for a field, these rules must run.

If you allow to ignore certain fields, add the [`if_exist` rule](http://codeigniter4.github.io/CodeIgniter4/libraries/validation.html#available-rules) and you are fine.

> If this rule is present, validation will only return possible errors if the field key exists, regardless of its value.

Works nice with Models, API updates, and HTML Forms.

Note that if you allow to ignore fields not sent in the Model, these will be ignored if you pass data direct from HTTP requests too...

**Comment by nowackipawel** [comment]
You are right as far as we don't have methods which are specified to update only part of fields defined in model. I.e. I've got user panel and I want to allow user to change her/his nickname without passing all her/his data to database . In that case imho is better to update only one field ( in updateUserNickName() method ) instead of reading entire user record, update one field, and pass it to database . My solution in this case has better performance: less rules to check , less (not necessary to get current record) and simpler queries , etc.
That's why I wrote PR updated models update() method which allows to validate ONLY fields available in my $data. I think every developer know that it could be dangerous if is using incorrectly.

I know it shouldn't work in that way in insert but I think it should in update if developer specify that he/she know what he/she is doing.

**Comment by natanfelles** [comment]
I like your approach. This way we will not need to use "if_exist" when we are sure which fields should be updated.

**Comment by nowackipawel** [comment]
I think the same :) There is a way to do exactly the same  with if_exist rule (with some bad hacks) but imho approach showed above is better.

**Comment by lonnieezell** [comment]
Looks like the core issue here has already been fixed.
