### ISSUE TITLE
Cannot define complex routes , i.e. date

### ISSUE THREAD

**Issue by nowackipawel** [codeigniter4/CodeIgniter4#1700]
I've tried to define simple placeholder for date:
i.e.:
```
^20[0-5][0-9]\\-(1[0-2]|0[1-9])\\-(3[0-1]|[0-2][1-9]) // double "-" escaping
```
or
```
(20[0-5][0-9]\\-(1[0-2]|0[1-9])\\-(3[0-1]|[0-2][1-9]))
```
but I get 
```
ErrorException

preg_match(): Unknown modifier '0' search →

SYSTEMPATH/Router/RouteCollection.php at line 1210
```
I think sth bad is happening here:
RouteCollection.php ::1192:
`
		preg_match_all('/\(([^)]+)\)/', $from, $matches);
`

**Comment by lonnieezell** [comment]
Well, for starters, those patterns doesn't work for me. When running standalone in [Patterns app](https://itunes.apple.com/us/app/patterns-the-regex-app/id429449079), I have to remove the `\\` escaping for the dash in order for it to accurately match anything. Since the dash is part of the date pattern you're looking, it's treated as part of the string here. Not sure if that is messing the system up or not. 

I'll write up a test to give it a try, though.

**Comment by lonnieezell** [comment]
Cannot replicate. In the routes file: 

```
$routes->addPlaceholder('date', '(20[0-5][0-9]-(1[0-2]|0[1-9])-(3[0-1]|[0-2][1-9]))');
$routes->get('(:date)', 'Home::dates/$1');
```

Visiting `http://localhost:8081/2018-01-12` takes me where I expect it to.
