### ISSUE TITLE
redirect()->to lost $baseURL config

### ISSUE THREAD

**Issue by baiyuxiong** [codeigniter4/CodeIgniter4#1721]
My config in App.php:
	public $baseURL = 'http://localhost/test/public';
	public $indexPage = 'index.php';

Code in  controller like this:
            return redirect()->to('/admin/home');

redirect url is :http://localhost/admin/home, but  http://localhost/test/public/index.php/admin/home expected.

**Comment by jim-parry** [comment]
This is not a bug. Redirecting to '/...' effectively eliminates the test/public part of your base url.
You should setup your server so that your project's public folder *is* the document root, and your baseurl would then be "http://localhost". If you want to host several sites, you will need Apache virtual hosts or else configure your server to dish the CI4 test site on a different port.

**Comment by baiyuxiong** [comment]
I think this is a bug.  ALL url  that not start with "http" should be prefixed by $baseURL. Virtual host makes things complicated.
