### ISSUE TITLE
PR#2012 caused 404 exception in spark 

### ISSUE THREAD

**Issue by nowackipawel** [codeigniter4/CodeIgniter4#2021]
This line: 
```
		$this->HTTPVerb = is_cli() ? 'cli' : Services::request()->getMethod();```
has been changed to:
```
		$this->HTTPVerb =  Services::request()->getMethod();
```

and this is the result
``

CodeIgniter CLI Tool - Version 4.0.0-beta.3 - Server-Time: 2019-05-22 14:22:25pm

ERROR: 404
Can't find a route for 'cimigrate'.

```

**Comment by MGatner** [comment]
Just found this myself (https://github.com/codeigniter4/devstarter/issues/2). The issue is that CodeIgniter.php's `spoofRequestMethod()` is actually setting the method on `clirequest` service (see `getRequestObject()`) and RouteCollection is always checking `request` service. I think there is no way around checking for CLI in the RouteCollection constructor.
