### ISSUE TITLE
The assets of the public_folder are not loaded

### ISSUE THREAD

**Issue by luispastendev** [codeigniter4/CodeIgniter4#2047]
Hi All!

The assets stored in the public folder are not loaded correctly, this problem only I have when I start my project with spark serve seems to be the content type of the files is not correct.

![imagen](https://user-images.githubusercontent.com/4117596/59152593-d805a500-8a0c-11e9-8d2e-da733ba36124.png)

This is how I charge my file
```
<link rel="stylesheet" href="<?= base_url('public/css/styles_landing.css') ?>" type="text/css"/>
```

It seems only to be a problem of spark since in Apache it does not happen

regards!

**Comment by lonnieezell** [comment]
Your website is expected to have it's document root set to the `public` folder, so `public` should never be in the URL - that's a safety feature. So you're right, spark will have issues with that, but that's by design.

If you need a different structure, than you'll need to edit [spark](https://github.com/codeigniter4/CodeIgniter4/blob/develop/spark#L33) to work for your situation.
