### ISSUE TITLE
$primaryKey forcefully 'needs' to be auto_increment

### ISSUE THREAD

**Issue by fefo-p** [codeigniter4/CodeIgniter4#2133]
**Describe the bug**
The primary key of my table is a combination of numbers and letters.
Using or not validation, a new record will not be saved to DB using Entities' save()

**CodeIgniter 4 version**
CodeIgniter Version: | 4.0.0-beta.4

**Affected module(s)**
Couldn't figure it out.

**Expected behavior, and steps to reproduce if appropriate**
A new record should be saved provided I include the primary key value.
Validation rules take care of it being a unique value.
`$numero`'s format is `##-#####/##` (12-34567/89)

https://pastebin.com/embed_js/Dz6JFnmk

**Context**
 - OS: Ubuntu 18.04.2 LTS
 - Web server Apache/2.4.29 (Ubuntu)
 - PHP version  7.2.19

**Comment by Tada5hi** [comment]
The reason for this is when you Provider the Primary key the Save Method
tries to perform an Update. So the Model Should Provide an Option to
specifiy if the primary key is Auto inctementing.

Fernando P <notifications@github.com> schrieb am Di. 13. Aug. 2019 um 00:26:

**Comment by fefo-p** [comment]
But, I do have a primaryKey to check if record exists or not. So save() method should be able to figure it out.
I don't see the need for it to be auto incrementing. Maybe just to return the "new id" once inserted into the DB. But that has another workaround

**Comment by MGatner** [comment]
That's the nature of `save()` - if it detects a primary key it assumes an update, otherwise it inserts. See https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Model.php#L529

If you need to force an insert (e.g. when your primary key doesn't exist) use `insert()`. I think any other approach would require an additional database call which would cripple the convenience of the `save()` shorthand.

**Comment by lonnieezell** [comment]
Sorry, that's not how the convenience function of save is meant to work, as @MGatner pointed out. Using `insert` and `update` separately will work fine for you, though.
