### ISSUE TITLE
Devstarter $salt

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#2156]
I'm not sure what failed in the deployment to devstarter (there have been a few of these issues reported) but it still has an old version of **app/Config/App.php** that includes `$salt`

**Comment by jim-parry** [comment]
The devstarter was a snapshot of the repo some 4-7 months ago, and it looks like it could use refreshing. I will do that this afternoon.

**Comment by jim-parry** [comment]
Just refreshed the devstarter base files. Does the repo work better for you now, after synching yours separate from composer update?

**Comment by MGatner** [comment]
This looks much better! I'm unfamiliar with the back-end deployment process but it would be great to have some automated sync from https://github.com/codeigniter4/CodeIgniter4/tree/develop to `appstarter`'s and `devstarter`'s "user files" (**app/**, **spark**, etc - anything not updated by Composer).

**Comment by jim-parry** [comment]
The appstarter is part of the release process, so updated in synch with the framework automatically. If there are flaws in the process, that needs to be fixed in the admin release scripts.

The devstarter is not part of any update or automatic process - it isn't tied to any release, but is instead meant to be "in progress". Maybe the repo needs to be rethought, and somehow have closer ties to the main one. The repo was created to helo my students work on merged but unreleased code, and it's serendipitous that it is useful for addin developers :-/

Maybe I'll start a thread for this on the forum, and see what we can come up with!

**Comment by MGatner** [comment]
Sounds good. Yeah I love the devstarter but it would be great if there were some way to do it so the user portions came from this repo's `develop` branch yet still had its own **composer.json** to handle the "guts". I'll think on it too - right now I'm using a janky script that installs the devstarter then clones `develop` from the main repo and replaces the files explicitly. 
https://github.com/tattersoftware/lighter/blob/develop/lighter
