### ISSUE TITLE
Problem with renaming deleted_at column inside model

### ISSUE THREAD

**Issue by medenboef** [codeigniter4/CodeIgniter4#2248]
If you use useSoftDelete and Dateformate as php timestamps inside a model a errornous sql will be  created. I  created  an integer column with default value 0. The created sql from a find request  to get the rows from the model  is   select * from users  where <<chosen name deleted>> is null, which results in a empty array.

**Comment by MGatner** [comment]
It looks to me like it is actually choking on escaping your `$deletedField`. Can you paste or PasteBin the top of your model file?

**Comment by medenboef** [comment]
Here it is:

        protected $DBGroup       = 'default';
        protected $table       = 'users';
        protected $primaryKey = 'id';
        protected $returnType = 'array';
        protected $useSoftDeletes = true;

        protected $allowedFields = [
'name',
'email',
'country'
         ];

        protected $useTimestamps = true;
        protected $dateFormat           = 'int';
        protected $createdField   = 'created_at';
        protected $updatedField   = 'updated_at';
        protected $deletedField   = 'deleted_at';

        protected $validationRules  = [
'name' =>'required|min_length[5]|max_length[32]',
'email'=>'required|valid_email|is_unique[users.email]',
'country'=>'required|alpha|exact_length[2]'
];
        protected $validationMessages = [];
        protected $skipValidation     = false;

thank you

Marco

Op di 24 sep. 2019 om 16:34 schreef MGatner <notifications@github.com>:

**Comment by michalsn** [comment]
> I created an integer column with default value 0

The default value for this field supposed to be `NULL` not `0`.

When `useSoftDeletes` option is enabled the actual query we're using is something like: 
```sql
SELECT * FROM `table` WHERE `table`.`deleted_at` IS NULL
```
Maybe we could consider introducing a `strictDeleteMode` or something? When enabled it would search for `0` for timestamp, or for an appropriate value (`0000-00-00 00:00:00` etc) for the date field.

The truth is it could be beneficial for some people with big data sets since it would use less data and index space.

But I don't have a strong opinion about this potential change.

**Comment by lonnieezell** [comment]
I hesitate to add yet another setting. I think unless we see this becoming a bigger problem we roll with it the way it currently is, where it checks for `null`.
