### ISSUE TITLE
Route can not work: Controller or its method is not found

### ISSUE THREAD

**Issue by brucelin** [codeigniter4/CodeIgniter4#2299]
When I add a route as the document described: 
```
$routes->add('products/([a-z]+)/(\d+)', '$1::id_$2');
```
But it shows the error:
```
Controller or its method is not found: \App\Controllers$1::id_12
```

**CodeIgniter 4 version**
rc-2.1

**Affected module(s)**
Router

**Context**
 - OS: Win7 
 - PHP 7.3.10
- Spark Server

Maybe Some regular expression **replacement** error occurred when match the uri.

**Comment by jim-parry** [comment]
If the first character of the "to" parameter is a dollar sign, as shown, then the first segment is not replaced at all.

In the example reported,  and with a test URI "/products/apple/222"
- a "to" value of "$1::id_$2" results in a controller name of "$1'
- a "to" value of "\$1::id_$2" results in a controller name of "\$1'
- a "to" value of "A$1::id_$2" results in a controller name of "\Aapple'

I can replicate the problem, but have been unable to solve it :(

**Comment by jim-parry** [comment]
@lonnieezell Is the user guide correct, that the above route should work as descibed.I don't want to bang my head against the wall if this is a writeup issue.

**Comment by lonnieezell** [comment]
I think the docs likely need to be changed to not show that example. It really doesn't make any sense and, if I wrote that, I apologize. :) 

While I think what you're trying to do there is technically possible, it's completely a bad idea. You should never let the URI specify the controller to run like that. Let auto-routing do it's magic, because if you start doing what that example shows, then a user can attempt to run any controller/method in the App\Controllers namespace. Especially when used with `$routes->add()` which works for all HTTP verbs. 

So, yes, that example needs to be changed! 

For a URI of `/products/apple/222` you'd want that to read something more like: 

```
$routes->get('products/([a-z]+)/(\d+)', 'Products::show/$1/$2 );
```

**Comment by brucelin** [comment]
> If the first character of the "to" parameter is a dollar sign, as shown, then the first segment is not replaced at all.
> 
> In the example reported, and with a test URI "/products/apple/222"
> 
> * a "to" value of "$1::id_$2" results in a controller name of "$1'
> * a "to" value of "$1::id_$2" results in a controller name of "$1'
> * a "to" value of "A$1::id_$2" results in a controller name of "\Aapple'
> 
> I can replicate the problem, but have been unable to solve it :(

I read the code and guess the problem may happen because when parsing the url to the controller class, the code join the namespace and controller name like **App\Controllers\\$1::id_$2**. Then the **\\$1** can not be a correct regular expression.  Maybe we can first parse the regular expression **$1::id_$2**, then attached it with the namespace.
