### ISSUE TITLE
Bug: localhost development server after edit the content not updated or reloaded

### ISSUE THREAD

**Issue by senthilmca90** [codeigniter4/CodeIgniter4#2363]
**Localhost development server**
Hi, I am using the `spark` localhost server. In the very first `php spark serve` when hitting the comment line and checking the browser `http://localhost:8080` it's working fine. After just open the `welcome_message.php` and edit the content it is not restarted the development server and not updated the browser. it loading... loading... loading... full day gone.

I attached the screenshot.

![image](https://user-images.githubusercontent.com/14997781/67563593-a3d21d00-f73e-11e9-9e42-25cd4f0ba84b.png)

**Context**
 - OS: [e.g. Windows 10]
 - Web server [e.g. Apache 1.2.3]
 - PHP version [e.g. 7.2.4]

**Comment by dafriend** [comment]
Without seeing what was done to "edit the content" it is impossible to determine where the bug might be.

**Comment by senthilmca90** [comment]
@dafriend I have edited the content like `<title>Welcome to CodeIgniter</title>` to `<title>Welcome to CodeIgniter1</title>`  for  `app/Views/welcome_message.php`. I couldn't find the error. it takes hug time, I didn't get any output, it keeps on loading...

**Comment by madspaz** [comment]
@senthilmca90 I see you have XAMPP running as well; for troubleshooting can you exit out of that since spark uses the built in PHP web server? I would hate to see that XAMPP somehow bound Apache to port 8080 as well (although I expect Spark would have failed to start the server at all). Can you also test this in another browser like Chrome or Firefox?

**Comment by lonnieezell** [comment]
Cannot replicate this and no further word from OP. Closing.
