### ISSUE TITLE
Bug: \CodeIgniter\Model::validate() returns TRUE if $data is empty

### ISSUE THREAD

**Issue by MashinaMashina** [codeigniter4/CodeIgniter4#2384]
**Describe the bug**
If model has in $validationRules required fields, but save entity is empty,  \CodeIgniter\Model::validate() returns TRUE, but must return FALSE, because field is required.

**Affected module(s)**
\CodeIgniter\Model

**Expected behavior**
return FALSE;

`<?php namespace App\Models;`
` `
`use CodeIgniter\Model;`

`class MyModel extends Model`
`{`
`		...`
`		`
`       protected $validationRules = [`
`			'project_id' => 'required'`
`		];`
`        protected $validationMessages = [];`
`        protected $skipValidation     = false;`
`		`
`		...`
` `
`}`

`$_POST = [];
$MyModel->save($_POST); // saved empty line in BD`

**Comment by MashinaMashina** [comment]
$rules = ['last_name' => 'required'];
$data = [];

$myModel->save($data)

I wants that last_name is required, but Model::cleanValidationRules() removes all rules. WTF??

**Comment by MGatner** [comment]
Validation is not run on empty data sets. Model line 1372:
```
if ($this->skipValidation === true || empty($this->validationRules) || empty($data))
```
This appears to have always been the case, though I can't say why. I agree that empty data sets should fail validation if there are certain rules set.

Though this might be a case for differentiating "update" versus "insert" validation rules, since updates allow partials and inserts should not. @lonnieezell ?

**Comment by lonnieezell** [comment]
I believe this was mostly for handling updates. And we might need to differentiate between those. 

To play Devil's Advocate, though, when you are you ever going to have an empty POST? If it's a form, then it will return field names unless they are all disabled. With a web form, that's an issue with your form design. If it's an AJAX call with JSON or whatever, it could potentially be a problem since the API can send an empty body but then the question becomes does not stopping on validation harm your app? Maybe, but likely not. If you're creating a new entity and your database is well designed it will throw an exception because it won't have required fields. Which you should be catching anyway. 

I know - probably lazy arguments lol. I kind of remember going through these logical questions while we were trying to fix that for inserts and not finding a perfect answer. I suppose we could add a setting to validation that decides whether it fails on empty data set or not. 

Open to other ideas, also.

**Comment by nowackipawel** [comment]
I want only to point out one PR: https://github.com/codeigniter4/CodeIgniter4/pull/2067 which can be related to this.
