### ISSUE TITLE
Bug: initController not called in ResourceController

### ISSUE THREAD

**Issue by aryaei2000** [codeigniter4/CodeIgniter4#2404]
**Describe the bug**
When extending ResourceController in a new controller, the initController is not called as the constructor.

**CodeIgniter 4 version**
4.0.0-rc.2.1

**Affected module(s)**
CodeIgniter\RESTful\ResourceController

**Expected behavior, and steps to reproduce if appropriate**
initController is supposed to be called on the event of creation of a new instance of the class.

**Context**
 - OS: Windows 10 
 - Web server  Apache 2.4.39 (Wamp)
 - PHP version 7.2.18

**Comment by dafriend** [comment]
It would be very helpful if you could provide code for a minimal, reproducible example. I think that means not only the controller extending `ResourceController` but probably also `ResourceController` itself along with any parents it might have.

**Comment by lonnieezell** [comment]
Code would definitely be helpful since I don't currently see any way this could be true. 

ResourceController [calls it's parent initController method](https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/RESTful/ResourceController.php#L77). 
And initController is [called by the main loop](https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/CodeIgniter.php#L823) on all controllers when it instantiates it.

**Comment by lonnieezell** [comment]
I just did a simple test: made the default Home controller that CI ships with extend ResourceController and everything loads as expected. I extended the initController method, and it's tried to run it as expected. 

Cannot find this a bug. Sorry. Post on the forums if you're stuck to get help with your situation.
