### ISSUE TITLE
form_input double escaping data why ?

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#2405]
hello i use this function form_input from the form helper like this, i don't know what i am doing wrong and don`t know if this is a bug or not but please test this.

`

	$input_attrs = array();
	$input_attrs['name'] = 'contact_name';
	$input_attrs['type'] = 'text';
	$input_attrs['id'] = 'contact_name';
	$input_attrs['class'] = 'form-control';
	$input_attrs['placeholder'] = 'Let us know what is your name.';
	$input_attrs['value'] = set_value('contact_name');

	echo form_input($input_attrs);

`
and when i put this value in the input <script>alert("test")</script>
it returns this : &amp;lt;script&amp;gt;alert(&amp;quot;test&amp;quot;)&amp;lt;/script&amp;gt;

But when i use without the form_input function and use it like this

`	

	<input type="text" name="contact_name" value="<?=set_value('contact_name')?>" id="contact_name" class="form-control" placeholder="Let us know what is your name.">

`

it returns good escaped data <script>alert("test")</script>.

Please someone tell me why when i use the form_input it gets double escaped or something...

**Comment by crustamet** [comment]
This was the worst thing happening in codeigniter 3 also :( horror stuff.. xD

This needs to end right ?

**Comment by dafriend** [comment]
It is not clear to me how and where you are introducing <script>alert("test")</script>

**Comment by lonnieezell** [comment]
I'm a bit confused about how this is bad: `&lt;script&gt;alert(&quot;test&quot;)&lt;/script&gt;` and this is good `<script>alert("test")</script>`? 

If someone is inputting a script in your form it should be caught and dealt with so that it does not execute when the form is redisplayed, or the data viewed. When the data is displayed in the input it is automatically escaped to make it safe. That's why you're seeing that.

**Comment by crustamet** [comment]
Hello again, i edited the problem so you guys can check please take this error bug into consideration, because on all other platforms this works and on this does not.
