### ISSUE TITLE
trailing slash cause redirect to root

### ISSUE THREAD

**Issue by hoceyn** [codeigniter4/CodeIgniter4#2445]
when I using this url :
`<?= base_url('dashboard/admin'); ?>`
result will this :
http://localhost:8888/mysite.com/public_html/dashboard/admin
it work properly.

but when I add trailing slash :
`<?= base_url('dashboard/admin/'); ?>`
it redirect to :
http://localhost:8888/dashboard/admin

- I didnt change .htaccess
- Im using mamp pro in mac
- apache server

**and this example work in CI3 .**

**Comment by lonnieezell** [comment]
Are you using the latest develop branch, or rc-3? We've fixed some URL issues since rc-3 that sounds like it might be related to this.

**Comment by StudPro** [comment]
I have the same issue. I used rc-3 and develop

Config
Apache on windows
htaccess: default from rc-3
env: 
app.forceGlobalSecureRequests = true
app.baseURL = 'https://localhost/ci4/'
Route: $route->add('landingpage','landingpage');

Controller
Into controller demo page do
redirect('landingpage) 
or redirect()->to('/landingpage');
or redirect()->to(route_to('landingpage'));

go to https://localhost/landingpage and not in https://localhost/ci4/landingpage

What am I doing wrong?

**Comment by tangix** [comment]
Like you I have the same problem. To workaround my problem I have patched the return from fillRouteParams() in system/Router/RouteCollection.php at line 1320 to:
`return ltrim($from, '/');`
In the original code in the develop branch a slash is added:
`return '/' . ltrim($from, '/');`
I have tried to whip up a PR but I can't get the tests to properly work with redirect().

**Comment by MGatner** [comment]
@hoceyn @StudPro Can you try again since Lonnie pushed some changes? https://github.com/codeigniter4/CodeIgniter4/issues/2505#issuecomment-578588461

**Comment by MGatner** [comment]
I haven't been able to replicate this, but I did find that preceding slashes get interpreted as relative to the domain root, rather than the subfolder. E.g.:
```
app.baseURL = 'https://localhost/ci4/'
echo base_url('/foo/bar');
```

The above will return "https://localhost/foo/bar" instead of "https://localhost/ci4/foo/bar". This seems to be an issue specific to `base_url()` since `HTTP\URI` should correctly return the former. I have a fix coming for that - maybe it will help these other issues?

**Comment by DeadOnTime** [comment]
For me this fixed the problem: https://stackoverflow.com/a/27264788

**Comment by noREAVER** [comment]
Had the same issue with the latest version.
Windows & apache 2.4
I used an alias for example _/site_ to map to the public folder
In this case you need to use _RewriteBase /site/_ 
The problem is that the default rule for removing trailing / is _RewriteRule ^(.*)/$ /$1_ but you have this / in /$1 which ignores the RewriteBase it seems, so to work you have to remove /  so _RewriteRule ^(.*)/$ $1_
Another weird thing was that this started to work as soon as i removed the cookie/site data from the browser only.
