### ISSUE TITLE
currentURL & previousURL doesnt work in parser

### ISSUE THREAD

**Issue by wingdu** [codeigniter4/CodeIgniter4#2460]
Hello,

if you want call {+ currentURL +} or {+ previousURL +} you get no output.

**Comment by lonnieezell** [comment]
Good catch. 

It does currently work to simply call the helper functions directly, though: `{+ current_url +}`

**Comment by wingdu** [comment]
Then its wrong in the documentation.

**Comment by lonnieezell** [comment]
Actually - docs are correct. It should be accessible through `currentURL`, but for some reason that plugin isn't getting fired when I tried it. But since the other functions, `current_url` and `previous_url` are always loaded the parser can find and use those. 

I need to figure out why the current plugins aren't working and whether they are worth keeping around since it works fine the other way.

**Comment by lonnieezell** [comment]
Turns out it was a docs issue after all. My bad.
