### ISSUE TITLE
[Docs] Loading Environment into Configuration documentation described wrong

### ISSUE THREAD

**Issue by JanZelenka** [codeigniter4/CodeIgniter4#2554]
**Describe the bug**
The documentation at [Docs » General Topics » Working With Configuration Files](https://codeigniter4.github.io/userguide/general/configuration.html) states the following:
_If the prefix of a namespaced variable matches the configuration class name exactly, case-sensitive, then the trailing part of the variable name (after the dot) is treated as a configuration property name._ 

This doesn't seem to work. What does work, though, is specifying the prefix in all lowercase, regardless of the class name capitalization. And since the examples in the **env** file are actually specified this way, I believe this is a documentation issue rather than any other.

**CodeIgniter 4 version**
4.0.0-rc.3

**Affected module(s)**
Config documentation

**Comment by MGatner** [comment]
It looks like it checks both the class name (which maybe requires namespacing?) and the "shortPrefix" which is indeed lowercased: https://github.com/codeigniter4/CodeIgniter4/blob/8d92dd0ef121ccacf3ea9811fee9e7676a25bb0f/system/Config/BaseConfig.php#L160

IMO you are right and this is a docs issue, the User guide should be updated to reflect the current behavior.

**Comment by dafriend** [comment]
The help file also shows `.env` examples with PascalCase prefixes.
Speaking of the _.env_ file, the docs could use a little section on where it is, how to use the example that's included, more clarity no how config classes and .env entries relate.

Shall I take a whack at all that?

**Comment by MGatner** [comment]
That would be tremendous! It is a frequent confusion on the forums so I’ve been meaning to see what we actually have in the UG and how we can beef it up. Anything you’d like to send over would be swell.

**Comment by dafriend** [comment]
I'm on it.

**Comment by dafriend** [comment]
While working through the code of ``BaseConfig::getEnvValue()`` I figured out how it actually works but would like some feedback (probably from @lonnieezell)  on if what I learned is the intended behavior.

With regard to [Incorporating Environment Variables Into a Configuration ](https://codeigniter4.github.io/CodeIgniter4/general/configuration.html#incorporating-environment-variables-into-a-configuration), the namespace prefix must be the whole namespace (case-sensitive) of the configuration class. For example, to set the ``SMTPPort`` value for the Email configuration from `.env` you have to use the following.

    Config\Email.SMTPPort = 587

And we know that the "short-prefix" form works too.

    email.SMTPPort = 587

If someone should use both of the above in the same file the short-prefix form will take precedence over the namespace prefix form. The order they appear in `.env` has no effect on which is applied. Should that be explained? 
Should that be changed?

The following forms will not work.

    config\email.SMTPPort = 587
    Email.SMTPPort = 587
    email.smtpport = 587

So, my question: Is all that the expected behavior?

It certainly seems to be, and I can make that clear in the docs. I just want to confirm before proceeding.

It's interesting to note that **all** the variations above (incorporated and not) will get placed in the `Environment`, `$_ENV`, and `$_SERVER` var spaces. I'm not sure we need to tell anybody that. Or do we?

**Comment by lonnieezell** [comment]
It wouldn't hurt explaining that, but this is the intended behavior.
