### ISSUE TITLE
Bug: Difficult architecture of the codeigniter4 project

### ISSUE THREAD

**Issue by atishamte** [codeigniter4/CodeIgniter4#2602]
CI installed using this command
composer create-project codeigniter4/appstarter -s rc --no-dev

I have gone through the released version of appstarter and found the dependency hierarchy is pretty weird like,

1. appstarter has a vendor directory
2. It has codeigniter4/framework directory
3. Inside this, again the entire CI hierarchy is present like, app, public, writable, system folder which is identical to appstarter directory structure

We can directly have the content inside of "appstarter\vendor\codeigniter4\framework\system\" to "appstarter\vendor\codeigniter4\".

This will only hold the core framework, not the other inappropriate things like app, public, writable,

**Comment by niteraven7** [comment]
Can confirm this as well.

**Comment by lonnieezell** [comment]
I believe Jim had left those other directories in place so that you could easily reference them to copy any changed files over. They do not conflict with operations. 

It's not a bug, and might be behavior that will change at some point, but not immediately. We have had discussions recently about this. Thanks for bringing it up.

**Comment by agungsugiarto** [comment]
Please open this issue again for remember.

agree with @atishamte, @lonnieezell yes is not conflict with operations, but why not deleted ? Codeigniter4/framework just need core system, folder like app, public, writeable etc is junk.

**Comment by atishamte** [comment]
I am not able to reopen it. @lonnieezell has to open this
