### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by fpp1602** [codeigniter4/CodeIgniter4#2608]
**Direction**
We use github issues to track bugs, not for support.  
If you have a support question, or a feature request, raise these as threads on our
[forum](https://forum.codeigniter.com/index.php).

**Describe the bug**
CodeIgniter CLI Tool - Version 4.0.1 - Server-Time: 2020-02-24 11:11:48am

An uncaught Exception was encountered

Type:        ErrorException
Message:     Cannot declare class CodeIgniter\Commands\CommandsTestStreamFilter, because the name is already in use
Filename:    C:\wamp64\www\codeigniter\codeigniter\tests\_support\Commands\CommandsTestStreamFilter.php
Line Number: 16

**CodeIgniter 4 version**
4.0.1

**Context**
 - OS: [Windows 10]
 - Web server [Apache]
 - PHP version [7.2]

**Comment by lonnieezell** [comment]
This is a known issue. I've reported it on the forum and in response to at least one issue here this morning. 

I'm out of time to work on the framework until late this evening, but we will get it taken care of ASAP. Thanks for reporting.

**Comment by lonnieezell** [comment]
Version 4.0.2 released that should fix all of this for a new install. Sorry about the release issues today.

**Comment by solaxes** [comment]
i updated version using composer update for CI4 version 4.0.2 but error is still there.

**Comment by solaxes** [comment]
CodeIgniter CLI Tool - Version 4.0.2 - Server-Time: 2020-02-26 02:05:39am

PHP Fatal error:  Cannot declare class CodeIgniter\Commands\CommandsTestStreamFilter, because the name is already in use in D:\projects\test\ci_4\ci-blog1\tests\_support\Commands\CommandsTestStreamFilter.php on line 16
An uncaught Exception was encountered

Type:        ErrorException
Message:     Cannot declare class CodeIgniter\Commands\CommandsTestStreamFilter, because the name is already in use
Filename:    D:\projects\test\ci_4\ci-blog1\tests\_support\Commands\CommandsTestStreamFilter.php
Line Number: 16

**Comment by solaxes** [comment]
i deleted previously installed CI4, installed fresh and its working fine now.
