### ISSUE TITLE
Bug: Request URI segment is our of range CI 4.0.3

### ISSUE THREAD

**Issue by desttools** [codeigniter4/CodeIgniter4#2949]
**Describe the bug**
I have code in my app structured like this:
`if ($request->uri->getSegment(2)){
...
}`

It evaluates fine in 4.0.2 and earlier, but breaks in 4.0.3, throwing this error:

`
CodeIgniter\HTTP\Exceptions\HTTPException
Request URI segment is our of range: 1 
`

**CodeIgniter 4 version**
4.0.3 master

**Affected module(s)**
Which package or class is the bug in, if known.

**Expected behavior, and steps to reproduce if appropriate**
Previously this returned NULL. Maybe my code needs to be updated to restructure this conditional? 

**Context**
 - ubuntu0.18.04.4
 - Apache/2.4.29 (Ubuntu)
 - PHP: 7.2.24-0

**Comment by samsonasik** [comment]
it seems you need to update your code, something like this:

```php
if ($request->uri->getTotalSegments() >= 2 && $request->uri->getSegment(2)) 
{

}

```
Just an example, not in front of pc ;)

**Comment by michalsn** [comment]
Oh, dear... I guess it's not gonna be very friendly to use in the long run... I haven't noticed this earlier but I would love to see this method to work similarly to one known from CI3. I guess it's a bit too late now.

Anyway... it's working that way from the beginning. No changes were made. You are experiencing this exception because it will always occur when you ask for a segment which number is greater than your total number of segments right now + 2.

**Comment by crustamet** [comment]
Yeah i had this issue i resolved like how **samsonasik** said.

Of course if you use this how the old CI3 worked, you will have many problems to fix.
That is why CI4 is better, they force you to fix stupid stuff happened to CI3.

All nice and dandy. I think it is better to verify the segment that you are not out of range to know exactly the route on which you on.

But there is another issue i had to workaround that i really don`t like and understand.
When you get segments and you have no segment in the url
it returns an array of two empty elements

```
$request->uri->getSegment(0);

returns [0=>'', 1=>''];
```
It is cool not that much of a deal i think they return like this because something from the core needs to be empty to verify the controller and the method.

I am sure they can fix this but it will change a lot of files.

**Comment by michalsn** [comment]
@crustamet I have to kindly disagree that in CI3 it was working "stupid". If you asked for a segment that wasn't there you always received a `null` in response. Personally, I would say the current implementation makes it more complicated to use.

**Comment by jreklund** [comment]
> It evaluates fine in 4.0.2 and earlier, but breaks in 4.0.3, throwing this error:

That part of the code are in 4.0.2 as well. The trow message where updated two years ago, and the function itself 5 years ago. So it have always worked that way. I guess you just have been lucky.

**Comment by samsonasik** [comment]
can be closed in favor of https://github.com/codeigniter4/CodeIgniter4/pull/3005

**Comment by braintech-mymd** [comment]
Just pass the current url while creating  object of URI class.
`$url = new \CodeIgniter\HTTP\URI(current_url());
        echo $url->getSegment(2);`

**Comment by kumar-kapil** [comment]
Just pass the current url when creating an object of URI class like below.
`$url = new \CodeIgniter\HTTP\URI(current_url());
        echo $url->getSegment(2);`
And please note that It is tested only with CI4 not with the previous versions.

**Comment by aknessy** [comment]
> Just pass the current url when creating an object of URI class like below. `$url = new \CodeIgniter\HTTP\URI(current_url()); echo $url->getSegment(2);` And please note that It is tested only with CI4 not with the previous versions. For more info you can visit [WebAppsPlanet](https://www.webappsplanet.com/)

Thanks for this @kumar-kapil

**Comment by biomedhed** [comment]
I agree with whoever posted about it being more complicated than CI 3 to get the segment. It used to send back null if it wasn't there.

I use segments all over the shop so migrating from CI3 to CI4 was a pain.

My solution was to create a customised Helper and within that create a new segment function that behaves the same as the CI3 one:

**function getSegmentProper(int $segment) : mixed {
    $uri = service("uri");
    $totalSegments = $uri->getTotalSegments();
    
    if ($segment > $totalSegments) {
        return null;
    }
    
    return $uri->getSegment($segment);
}**

In the calling code just use e.g.:

$segment5 = getSegmentProper(5);

and autoload the Helper in the config.

Not saying it's the perfect solution but saved me a lot of time and code.

**Comment by michalsn** [comment]
@biomedhed A much simpler solution is to call `$uri->setSilent()` in your base controller, this way you will get the same behavior as we had in CI3, see: https://codeigniter.com/user_guide/libraries/uri.html#uri-segments

**Comment by biomedhed** [comment]
> [@biomedhed](https://github.com/biomedhed) A much simpler solution is to call `$uri->setSilent()` in your base controller, this way you will get the same behavior as we had in CI3, see: https://codeigniter.com/user_guide/libraries/uri.html#uri-segments

Didn't even know about that method. Will look into it, ta.
