### ISSUE TITLE
Bug:  Not possible manipulate results of renderSection() on View Layouts

### ISSUE THREAD

**Issue by natanfelles** [codeigniter4/CodeIgniter4#3028]
**Describe the bug**
It is not possible to manipulate the string result of a View Layout `$this->renderSection()` without using ob_* functions due the void function works with `echo` and not `return`.

https://github.com/codeigniter4/CodeIgniter4/blob/6d019e5354629fa7c1e293c2f463d91004c6e26c/system/View/View.php#L496-L510

This example https://codeigniter4.github.io/userguide/outgoing/view_layouts.html#creating-a-layout show a echo but it is not necessary.

**CodeIgniter 4 version**
4.0.3

**Affected module(s)**
View Layouts

**Expected behavior, and steps to reproduce if appropriate**

Expect to can save result of `renderSection()` in a variable.

**Context**
 - OS: Ubuntu
 - Web server [PHP built in]
 - PHP version [7.4]

**Comment by samsonasik** [comment]
@natanfelles I created PR #3031 for it.

**Comment by lonnieezell** [comment]
> This example https://codeigniter4.github.io/userguide/outgoing/view_layouts.html#creating-a-layout show a echo but it is not necessary.

You're right, it's not necessary but it's a cleaner syntax than using full tags. 

You did not state why this is  a problem. What's your use case for needing to do that?

**Comment by natanfelles** [comment]
I have a layout with meta description:

```
<meta name="description" content="<?= $this->renderSection('description') ?>">
```
It works nice. But I need to show the meta only if the section has content.

So:

```
<php if( $this->renderSection('description')): ?> // <-- the problem
<meta name="description" content="<?= $this->renderSection('description') ?>">
<?php endif ?>
```
But it is not posssbile because `renderSection` do not `return`, it `echo`

**Comment by samsonasik** [comment]
@natanfelles in #3031 I added 2nd parameter `$echoed` that can be set to false for that to avoid bc break.

**Comment by lonnieezell** [comment]
Sorry, I don't find this a good use case. The whole purpose of the templating features are for templating, not for conditional logic. By using it in the way you are here, you're processing the contents of that section twice, which is an unnecessary performance hit, also. 

I can't see very many reasons why you can't handle meta values in the controller or a library and pass it in. You already know the data going into that view so can make the determination in the controller layer instead of the view layer. If you're using View Cells and that's the issue, then you could fire off an event that collects all of the meta data from all of your systems into an array or class, then pass that into your view layer.

**Comment by natanfelles** [comment]
```
$desc = $this->renderSection('description'); // <-- the problem
<php if($desc): ?> 
<meta name="description" content="<?= $desc?>">
<?php endif ?>
```

There is no way to set values from an extended to a main layout. I will try View Cells.

**Comment by natanfelles** [comment]
Oh, tested with `$this->setVar('description', 'abc123');` on an extended layout and it is possible pass the `$description` variable to the main layout.
