### ISSUE TITLE
valid_url does not work correctly

### ISSUE THREAD

**Issue by luispastendev** [codeigniter4/CodeIgniter4#3156]
Hello!

Url validation doesn't work, if I pass a string like this `asdf` it passes the validation which should be wrong

my validation is as follows:
```php
'rules' => 'permit_empty|valid_url|max_length[512]'
```

Hugs!

**Comment by crustamet** [comment]
Tell us what is the expected result bro.
From my point of view the rule works correctly
asdf can be a valid url if you use localhost with some proxy or what not.
Just like localhost is a valid url, asdf is the same.

If you want to prepend the HTTP or HTTPS just use prep_url on the input.

**Comment by michalsn** [comment]
Not a bug, sorry - `asdf` is a valid hostname.

Please take a look at [RFC 2396](http://www.faqs.org/rfcs/rfc2396) - these are the rules behind `FILTER_VALIDATE_URL`.

But we're open to adding a new rule that will be more "restrictive".

**Comment by MGatner** [comment]
I'm reopening this issue because I think there are some things that need to be addressed.

1. `RFC 2396` is obsolete. The new doc is [RFC 3986](https://tools.ietf.org/html/rfc3986)
2. The spec differentiates between "URI" (Identifier) and "URL" (Location). A URL:

> The  term "Uniform Resource Locator" (URL) refers to the subset of URIs that, in addition to identifying a resource, provide a means of locating the resource by describing its primary access mechanism (e.g., its network "location").

3. The section ["Syntax Components"](https://tools.ietf.org/html/rfc3986#section-3) describes the parts of the URI. Of note, it *requires* a scheme (e.g. "https") but not a path:

> The scheme and path components are required, though the path may be empty (no characters)

4. Our current validation rule very clearly allows the opposite in order to validate "common" URLs like "CodeIgniter.com". See also the validation rules tests for some wonky passes (https://github.com/codeigniter4/CodeIgniter4/blob/d9864e33758aca9aca9dc44c121e402e2d51136f/tests/system/Validation/FormatRulesTest.php#L88)

Here's my opinion:

a) We need `valid_url_strict` or something that has a lower tolerance for actual URLs.
b) I think the current validator should *not* pass simple strings like "asdf", but in order to prevent a breaking change we should still accept "CodeIgniter.com". Probably could check for a scheme and pass to a) if found, use a simple regex otherwise.

Just to note, Laravel and Symfony use a super convoluted regex to check validity (https://github.com/laravel/framework/blob/cb398188729f51e63d6fd0dc1ed9009fcf76b404/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1732).

**Comment by MGatner** [comment]
One more comparison, the list of Symfony's invalid URLs test:
```
            ['example.com'],
            ['://example.com'],
            ['http ://example.com'],
            ['http:/example.com'],
            ['http://example.com::aa'],
            ['http://example.com:aa'],
            ['ftp://example.fr'],
            ['faked://example.fr'],
            ['http://127.0.0.1:aa/'],
            ['ftp://[::1]/'],
            ['http://[::1'],
            ['http://hello.☎/'],
            ['http://:password@symfony.com'],
            ['http://:password@@symfony.com'],
            ['http://username:passwordsymfony.com'],
            ['http://usern@me:password@symfony.com'],
            ['http://nota%hex:password@symfony.com'],
            ['http://username:nota%hex@symfony.com'],
            ['http://example.com/exploit.html?<script>alert(1);</script>'],
            ['http://example.com/exploit.html?hel lo'],
            ['http://example.com/exploit.html?not_a%hex'],
            ['http://'],
```

**Comment by michalsn** [comment]
I only disagree with point b) - resolving addresses to http is default behavior. If we use a web browser or wget it will work. The same situation is here. If we agree that `codeigniter.com` is a valid address then `asdf` has to be valid as well.

**Comment by MGatner** [comment]
I get that it is a slippery slope, but I think we are dealing with expectations here. I ended up on this issue from a very user-based perspective: I could not get my tests to work because “foobar” was passing as a URL. Having a validation rule that passes almost any string of consecutive characters weakens it. In order to get my tests working I had to track down the actual rule code and determine that a space would invalidate it (“foo bar”) which we should be expecting of devs. 

I could see explicit exceptions for common strings one might use (like “localhost”) but I think the current rule is neither RFC-accurate nor helpful.

**Comment by michalsn** [comment]
Valid point about user expectations, but IMO these expectations should not lead to the inconsistencies that are impossible to defend in the technical discussion. And I'm referring just to omitting the protocol.

**Comment by MGatner** [comment]
Understood. I’m not very invested in it either way - personally I think `valid_url` is rather useless and (when it is written) `valid_url_strict` will cover my use-cases. I think as long as the docs are clear about what the code actually does - “Fails if field does not contain a valid URL” is both wrong and misleading. 

On the topic, I’ve been wondering if validation should be added to the URI class, since it appears to be more complicated than just a regex or PHP command. `valid_url_strict` could then leverage `URI::validate()`.

**Comment by MGatner** [comment]
> inconsistencies that are impossible to defend in the technical discussion

How about this as a rubric: `valid_url` passes anything you can type into a browser location bar (not including search results). This pretty much encapsulates the desire to support "shorthand" URLs (like CodeIgniter.com) while helping mitigate failed developer expectations (like if a user types their username in the wrong box, suddenly "michalsn" is a valid URL).

**Comment by michalsn** [comment]
I think I would only mention that if the protocol part in the address is omitted it will be added automatically before doing a check. This is just more accurate and nobody will have doubts about how things are working.

About `URI::validate()` - it's a good idea. If I remember it correctly we're using `parse_url()` in URI class.

> On seriously malformed URLs, parse_url() may return FALSE.

I wonder how many false-positive results we can get.

**Comment by crustamet** [comment]
From my perspective first when i've installed this codeigniter 4 i used this rule, and put asdf myself and found out that was a valid url pissed me off a little, after complaining on this issue here on github, someone closed the topic said it was valid. It made good sens for a while and used parse_url to fix the problem even tough the url wasn`t valid we can make it valid with parse_url function.

After testing with some browsers, i found out that if you type asdf in the url, it will go to the default search automatically type this asdf inside the search text box.

Weird how the web evolved... even if we type mistakes it will get automatically fixed. 

However they must be valid urls but i think you have to put minimum at least 2 characters to be valid url no ?

**Comment by Instrye** [comment]
In my opinion. `valid_url` should only allow URL to pass inspection. Such `asdf `, `localhost`, `codeigniter.com` string, it not a URL. It 's domain.

**Comment by crustamet** [comment]
it is always a good practice to use prep_url to be sure it will be a valid url, even if you type asdf the prep_url will prepend http:// to it.

**Comment by aqilfiqran** [comment]
> Hello!
> 
> Url validation doesn't work, if I pass a string like this `asdf` it passes the validation which should be wrong
> 
> my validation is as follows:
> 
> ```
> 'rules' => 'permit_empty|valid_url|max_length[512]'
> ```
> 
> Hugs!

`asdf` not an url

**Comment by kenjis** [comment]
I sent another PR: #5268
