### ISSUE TITLE
4.0.3 Bug: Call to undefined method CodeIgniter\HTTP\RedirectResponse::withCookies()

### ISSUE THREAD

**Issue by gosocial2** [codeigniter4/CodeIgniter4#3315]
**Bug Description**
The following exception is thrown when user tries to login in a myth-auth integrated project:
Call to undefined method CodeIgniter\HTTP\RedirectResponse::withCookies()

When the following is executed 
`return redirect()->to($redirectURL)->withCookies()->with('message', lang('Auth.loginSuccess'));`
from VENDORPATH/myth/auth/src/Controllers/AuthController.php at line 99

**CodeIgniter 4 version**
4.0.3 release (non-dev)

**Affected module(s)**
CodeIgniter\HTTP\

**Expected behavior**
Please stop making breaking changes, and maintain framework stability across all minor versions, as we want to be able to use and support CI4, and not seek stability elsewhere.

**Context**
- PHP version 7.3.x

**Comment by lonnieezell** [comment]
It is not a breaking change. It a new feature to the core of CI. Since Myth:Auth is in beta, there is no promise of stability there and this breaking issue is better targeted at Myth:Auth :)  The notes on Myth:Auth do state that the latest version requires the develop branch of CI4 to work due to this. 

Luckily 4.0.4 is expected to drop tonight with that fix in it, with a new release of Myth:Auth right around the corner.
