### ISSUE TITLE
Why redirect()->to() doesn't work inside events Model?

### ISSUE THREAD

**Issue by reszko** [codeigniter4/CodeIgniter4#3346]
I have an model event, beforeUpdate that runs a code that checks something.
I would like to use the redirect()->to() function inside this model event, but when I use it, it does not redirect from model.

**This does not work:**
`return redirect()->to('/new_locale')`;

It is just ignored and de program flux continues;

**This works:**
`header("Location: /new_locale");
die();
`

The code above are inside a method that is called from beforeUpdate propertie inside model

Thank you.

**Comment by MGatner** [comment]
The `redirect()` function actually creates a `RedirectResponse` which, to be effective, needs to be returned by a Controller so the core can execute it. Calling the function anywhere else is basically just creating a response class that does nothing. 

If you really need to redirect from some unusual place consider using a `RedirectException`. I think most of the time this is a crutch and there’s a better means of handling the intercept, but it’s a bit more tidy than calling `header()` in the middle of nowhere.

**Comment by mxmp210** [comment]
Anyone who wants to redirect a route forcefully,
You just need to send Response to browser
You can do it by 
`redirect('<route>','location',304)->send();`

Reason :
Redirect function creates `RedirectResponse ` object which is consumed by CI runtime and the class is extended upto MessageInterface. Because only controller methods are excepted to create Messages i.e. Response and Request objects, it defaults to creating proper response object which is built and then proper send method is called. While outside controller function the sending is not done by core / kernel and thus no response is sent to browser.

Caution :
Do not try to send redirect responses if you are sending body with it, it will end up with error 'Headers are already sent' or may end up not redirecting at all. Remember you only need to set Location header to create redirecting functionality work with browsers.

Hope this helps anyone who is stuck with documentation.
