### ISSUE TITLE
Support PSR4

### ISSUE THREAD

**Issue by fanqingxuan** [codeigniter4/CodeIgniter4#3405]
Psr4 specification has been supported by the famous framework like symfony,laravel. I think CI4 also shoud it .But it seems not, For example, all the config files namespace should be App\Config, but now the namespace is Config. in the config directory

**Comment by lonnieezell** [comment]
We do support PSR4 standard. Our autoloader is built around it. The Config namespace is an additional namespace root that's been defined, but even it supports PSR4 within it. Theoretically, you could namespace files to App\Config, but since the developer has the option to change the main namespace of the app, we had to provide a way for config files to always be found by the system, even before the autoloader had been loaded. So we added a main Config namespace to handle that.
