### ISSUE TITLE
Bug: Model insert method always insert with current datetime on updatedField

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#3469]
Hello i have this issue when i insert a new record always insert with updateField current datetime even if the field is default NULL

I inserted a new record raw from my mysql db to check if mysql automatically inserts this but it is not.

Insert Method from Codeigniter Model has inside these lines

from line 798 - 806

	if ($this->useTimestamps && ! empty($this->createdField) && ! array_key_exists($this->createdField, $data))
	{
		$data[$this->createdField] = $date;
	}

	if ($this->useTimestamps && ! empty($this->updatedField) && ! array_key_exists($this->updatedField, $data))
	{
		$data[$this->updatedField] = $date;
	}

Why the $this->updatedField is even checked here ?

**Comment by crustamet** [comment]
I suggest these following lines should be removed from Model public function insert()

	if ($this->useTimestamps && ! empty($this->updatedField) && ! array_key_exists($this->updatedField, $data))
	{
		$data[$this->updatedField] = $date;
	}

**Comment by michalsn** [comment]
This is intended. You can extend the Model class and make changes or prepare a PR to make it configurable. Personally I see no issues with current behavior.

**Comment by crustamet** [comment]
I understand, but can i ask why it is intended ?

I just don't understand the reason, why when you create something has modified date set instead of NULL.

Really there is no issue but the thinking is wrong. And because of this all system works the same way.

Think about it when something is created has a modified date on it ?
Why would you make the modified date become the same as created date, just to fill up space for nothing ?

**Comment by michalsn** [comment]
Because most of the time it's way easier to work with. There are basically two approaches to this. One is presented by you, and the second one implemented in the Model class. IMO there is no right or wrong solution here. There are trade-offs in both cases.

E.g. if we would like to sort records by `updateField` we would have to use `COALESCE` which performs not so great with `ORDER` and also creates more complicated code. The size of the dataset is not always a primary concern to the developers. The decision not to use `null` was made to make life easier for developers.

**Comment by crustamet** [comment]
Thanks for reply. I really appreciate your answers.

It seems like if you have updateField to null, you will have to sort the rows by two fields instead of one, still don't know why you would use COALESCE if updateField was null ?

The sort works the same with only ORDER BY.

Anyway, for me it does not make life easier but works fine like this.. i just had to tweak my queries a little.
