### ISSUE TITLE
Bug: SQLite3 NOT NULL prevents inserts

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#3599]
**Describe the bug**
I'm a SQLite noob so maybe someone can correct me... but I've been using it more in testing since it is so fast with `:memory:`. However, I just ran into this issue today that a `NOT NULL` field (the default, unless your migration specifies `'null' => true`) will fail on inserts without data specified. Example error:

> ErrorException: SQLite3::exec(): NOT NULL constraint failed: db_users.flair

Consider the following migration:
```
$fields = [
	'name'       => ['type' => 'varchar', 'constraint' => 63],
	'flair'      => ['type' => 'varchar', 'constraint' => 63],
	'created_at' => ['type' => 'datetime', 'null' => true],
	'updated_at' => ['type' => 'datetime', 'null' => true],
];
$this->forge->addField('id');
$this->forge->addField($fields);

$this->forge->createTable('users');
```

Very standard. Then my `UserModel` can do this:
```
$model->insert(['name'  => 'Zaboomafoo']);
```

In MySQL this will create a row with `""` for `flair` since it is a `VARCHAR` with no input specified. In SQLite3 I get the above error. Best I can tell (see e.g. https://github.com/cakephp/phinx/issues/265) when a SQLite3 column is `NOT NULL` it needs to have a default value specified to prevent this.

Anyone?

**CodeIgniter 4 version**
`develop`

**Affected module(s)**
Database - Forge - SQLite3

**Context**
 - OS: Ubuntu
 - Web server: Apache
 - PHP version: 7.3

**Comment by michalsn** [comment]
Seems like a proper behavior to me. If MySQL is running in the strict mode (and I'm quite sure it's the default setting where `STRICT_TRANS_TABLES` is present in `sql_mode`) you will get the same result (error).

Personally I would advise using strict mode whenever it's possible.

**Comment by MGatner** [comment]
Maybe I've been trained poorly with MySQL but I only add NULL to VARCHAR fields if I need an additional state. I.e. if NULL and `""` actually mean something different. When creating a MySQL field it defaults to NOT NULL unless otherwise specified, so adding a column without a specified field will set it to `""` out the box, per se. 

Regardless, it seems that having "standard" migrations + seeds fail on different drivers should not happen.

**Comment by michalsn** [comment]
Of course `NULL` and `""` (empty string) means something different but if you set the database field as `NOT NULL` (without `DEFAULT`) and at the same time you don't specify the value for that field during `INSERT` -  the error is something I would always expect to happen.

I believe that this is the default behavior for all databases: SQLite3, PostgreSQL, and MySQL. The problem with this last database is a bit of a CodeIgniter fault. We don't use the strict mode (default for this DB) when we establish the connection. This behavior was ported from CI3. I think that some time ago it had sense since from what I remember `STRICT_TRANS_TABLES` was not always the default setting - so I guess it was something introduced for compatibility reasons.

Differences between drivers in this case purely depend on a mode we want to use during connection to MySQL (`strictOn`). When we will use strict mode in our connection settings for MySQL, it will behave the same as other databases.

**Comment by MGatner** [comment]
I see, that makes sense. I will do a little more testing before I make up my mind about whether this behavior merits changing.

**Comment by michalsn** [comment]
When it comes to changes - personally I would go with a strict mode on for MySQL, but that would probably result in hiring a high-class hitman by the community to assassinate us 😅 Idk maybe this kind of change would fit the v4.1?

**Comment by MGatner** [comment]
I imagine it would be a major breaking change and would need to be for version 5. Do we have a way to create a strict connection with the MySQL driver currently? Like an option on the Config? If not definitely we should add that. Alternatively, if it constitutes deeper changes than just a connection flag perhaps we could make a new driver that extends the current one?

**Comment by michalsn** [comment]
Switching the variable will do the trick - it's already built-in: https://github.com/codeigniter4/CodeIgniter4/blob/develop/app/Config/Database.php#L49
