### ISSUE TITLE
Bug: Connection ID unknown immediately after connection

### ISSUE THREAD

**Issue by lf-uraku-yuki** [codeigniter4/CodeIgniter4#3601]
**Describe the bug**
Immediately after connecting to DB using \Config\Database::connect('group_name'), the connID of DB cannot be obtained. You will be able to see the connID after executing some SQL. I found it when using Postgre.

**CodeIgniter 4 version**
4.0.4

**Affected module(s)**
CodeIgniter\Database\Postgre

**Expected behavior, and steps to reproduce if appropriate**
Execute \Config\Database::connect('group_name') to get the public connID of the returned object.

**Context**
 - OS: Windows 10 2004 64bit
 - Web server is [php spark server]
 - PHP version 7.4.9 x86_64 Thread Safe

**Comment by michalsn** [comment]
This is intentional. It's made that's way to avoid unnecessary database connection. You may have database class loaded globally and an immediate connection is not always needed as we may not use the database at all for some pages. Therefore the connection takes place only when the first query is called.

If you want to connect immediately - before you run any query, just call the `initialize()` method.

```php
$db = \Config\Database::connect();
$db->initialize();
```

**Comment by lf-uraku-yuki** [comment]
Thank you for answering.
