### ISSUE TITLE
The isAJAX method does not exist in filters

### ISSUE THREAD

**Issue by luispastendev** [codeigniter4/CodeIgniter4#3604]
I need to do a comparison inside a filter to know if $request is of type ajax. but it seems that the method loaded in the callback is not there: 

```php
public function before(RequestInterface $request, $args = null){
    if($request->isAJAX()){ // <- not defined method
          ......
    }
}
```

I think that method should be inside the request since until now it could only be solved in the following way:

```php
if($_SERVER['HTTP_X_REQUESTED_WITH'] == 'XMLHttpRequest'){
    ....
}
```

greetings

**Comment by MGatner** [comment]
The method definitely exists, `IncomingRequest` line 279:
```
public function isAJAX(): bool
```

You may have something wrong with your installation, or perhaps using a custom `Request` object? Since Filters receive `RequestInterface $request` it isn't necessarily an `IncomingRequest`. Add this to your filter to see what kind of object you're actually getting: `dd($request);`

**Comment by samsonasik** [comment]
I can't reproduce, I used it in https://github.com/samsonasik/ci4-vue project and working OK:

https://github.com/samsonasik/ci4-vue/blob/7572347636babc30cadb4ea91cca6e6c7e3508d5/app/Filters/LayoutUsage.php#L11-L17

**Comment by michalsn** [comment]
I couldn't reproduce it either. What version of CI are you using?

**Comment by luispastendev** [comment]
OMG A thousand apologies for raising this stupid issue, I was distracted, it works correctly but it seems to have been some problem with the linter I'm using! I close the issue :(
