### ISSUE TITLE
CodeIgniter\Database\Exceptions\DatabaseException #8  Unable to connect to the database. 

### ISSUE THREAD

**Issue by ridho008** [codeigniter4/CodeIgniter4#3639]
CI_ENVIRONMENT = development
app.baseURL = 'http://localhost:8080/'
database.default.hostname = localhost
database.default.database = ci4
database.default.username = root
database.default.password =
database.default.DBDriver = MySQLi

Controller Komik.php
<?php namespace App\Controllers;

class Komik extends BaseController
{
	public function index()
	{
		$data = [
			'judul' => 'Daftar Komik'
		];

		// cara konek db tanpa model
		$db = \Config\Database::connect();
		$komik = $db->query("SELECT * FROM komik");
		dd($komik);

		return view('komik/index', $data);
	}

}

My Model
<?php
namespace App\Models;

use CodeIgniter\Model;

class KomikModel extends Model {
	protected $table = 'komik';
	protected $useTimestamps = true;
}

i user xampp

**Comment by MGatner** [comment]
You do not appear to have added your database settings, therefor CodeIgniter can not connect.

**Comment by fraznistpunk** [comment]
> You do not appear to have added your database settings, therefor CodeIgniter can not connect.

I am facing the same issue, can you please elaborate. Thanks in advance.

**Comment by MGatner** [comment]
CodeIgniter tried to connect to the database you have configured in .env (or app/Config/Database.php, but I highly recommend using .env). The error posted here is when it cannot connect, often because the configuration has not been sent. 

See

**Comment by fraznistpunk** [comment]
> CodeIgniter tried to connect to the database you have configured in .env (or app/Config/Database.php, but I highly recommend using .env). The error posted here is when it cannot connect, often because the configuration has not been sent.
> 
> See https://codeigniter4.github.io/userguide/database/configuration.html

I have all my database info in .env file instead of Database.php, i am using Linux(Kali) and xampp server

**Comment by blackforestcode** [comment]
> CodeIgniter tried to connect to the database you have configured in .env (or app/Config/Database.php, but I highly recommend using .env). The error posted here is when it cannot connect, often because the configuration has not been sent.
> 
> See https://codeigniter4.github.io/userguide/database/configuration.html

I have the same issue. All database credentials set in .env, but no connection (even not working if I set up in Database.php instad of .env).

What do you mean with "...often because the configuration has not been sent."? Could you make this a little bit clearer, please?

**Comment by lonnieezell** [comment]
Many times replacing `localhost` with `127.0.0.1` will get your database working.

**Comment by blackforestcode** [comment]
> Many times replacing `localhost` with `127.0.0.1` will get your database working.

My database is remote. With CI3 it works without problems. I've setup a new CI4 installation today, but DB-connection fails.

**Comment by paulbalandan** [comment]
Try setting your error logging threshold to `4` instead of the default `3`. Then retry. In your logs you will now see the specific error message thrown by the database connection.

**Comment by blackforestcode** [comment]
> error logging threshold

Okay, done. These are the error messages:

`ERROR - 2020-09-15 09:04:13 --> Error connecting to the database: Call to undefined function CodeIgniter\Database\MySQLi\mysqli_init()`

and 

`CRITICAL - 2020-09-15 09:04:13 --> Unable to connect to the database.`

with this file relations:

`#0 /.../Codeigniter4/crm/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()`

`#1 /.../Codeigniter4/crm/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query()`

`#2 /.../Codeigniter4/crm/vendor/codeigniter4/framework/system/Model.php(398): CodeIgniter\Database\BaseBuilder->get()`

`#3 /.../Codeigniter4/crm/app/Controllers/Auth.php(23): CodeIgniter\Model->find()`

`#4 /.../Codeigniter4/crm/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Auth->sign_in()`

`#5 /.../Codeigniter4/crm/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController()`

`#6 /.../Codeigniter4/crm/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest()`

`#7 /.../Codeigniter4/crm/public/index.php(45): CodeIgniter\CodeIgniter->run()`

`#8 /.../Codeigniter4/crm/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(34): require_once('/...')`

`#9 {main}`

**Comment by paulbalandan** [comment]
> `ERROR - 2020-09-15 09:04:13 --> Error connecting to the database: Call to undefined function CodeIgniter\Database\MySQLi\mysqli_init()`

Here's your error message. It seems you are using the `MySQLi` driver but your PHP installation has `mysqli` extension not installed or activated. In your php.ini, you can remove the semicolon in `; extension = mysqli`

**Comment by blackforestcode** [comment]
> > `ERROR - 2020-09-15 09:04:13 --> Error connecting to the database: Call to undefined function CodeIgniter\Database\MySQLi\mysqli_init()`
> 
> Here's your error message. It seems you are using the `MySQLi` driver but your PHP installation has `mysqli` extension not installed or activated. In your php.ini, you can remove the semicolon in `; extension = mysqli`

Oh man, now everything is clear to me! Yes, you are right, the mysqli extension was not installed. 
Let me say it like Homer Simpson: "Doh!".  😄 

I hadn't noticed that, because I always started Codeigniter 3 with MAMP before,, but with Codeigniter 4 I'm now starting with php spark.

Thanks a lot man! 👍

**Comment by reyzapoteto** [comment]
you can change the password and the username based on your phpmyadmin

**Comment by udarht** [comment]
> CI_ENVIRONMENT = development
> app.baseURL = 'http://localhost:8080/'
> database.default.hostname = localhost
> database.default.database = ci4
> database.default.username = root
> database.default.password =
> database.default.DBDriver = MySQLi
> 
> Controller Komik.php
> 
> 'Daftar Komik' ]; // cara konek db tanpa model $db = \Config\Database::connect(); $komik = $db->query("SELECT * FROM komik"); dd($komik); return view('komik/index', $data); } } My Model

Check ur port. 
if u do change that. Please change on app\Config\Database.php
default port => 3306 //change this for ur setting on database
and if u do change hostname, example
localhost:8088
change to : 
127.0.0.1:8088

**Comment by IrfanIndraKurniawan** [comment]
Thanks All.. it work in my linux

sudo apt-get install php-mysql

**Comment by InesAyari** [comment]
Hello ,
I am working on an application already developed with codeignter for the first time, I had imported the application from git on my computer but I cannot connect to the database, I still have this error message , I need help getting started adding new features to this app.

**Comment by MGatner** [comment]
@InesAyari Please take support questions to the forums or Slack.

**Comment by Jobayer-Tuser** [comment]
> Many times replacing `localhost` with `127.0.0.1` will get your database working.

thanks man this work for me

**Comment by touhidalam09** [comment]
**Enable php mysqli Extension** from php.ini file in php folder

- [ ] `;extension=mysqli` just remove `;` like this `extension=mysqli`

it's work for me. Thank You.

**Comment by MdFarzan** [comment]
> Many times replacing `localhost` with `127.0.0.1` will get your database working.

It works man, thanks buddy.

**Comment by prashantgawai1** [comment]
mysqli.default_port

**Comment by Hammad-Willowbyte** [comment]
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
SYSTEMPATH\Database\BaseConnection.php at line 400

393                         break;
394                     }
395                 }
396             }
397 
398             // We still don't have a connection?
399             if (! $this->connID) {
400                 throw new DatabaseException(sprintf(
401                     'Unable to connect to the database.%s%s',
402                     PHP_EOL,
403                     implode(PHP_EOL, $connectionErrors)
404                 ));
405             }
406         }
407 
Backtrace Server Request Response Files Memory
SYSTEMPATH\Database\BaseConnection.php : 570   —  CodeIgniter\Database\BaseConnection->initialize ()

563      * @todo BC set $queryClass default as null in 4.1
564      */
565     public function query(string $sql, $binds = null, bool $setEscapeFlags = true, string $queryClass = '')
566     {
567         $queryClass = $queryClass ?: $this->queryClass;
568 
569         if (empty($this->connID)) {
570             $this->initialize();
571         }
572 
573         /**
574          * @var Query $query
575          */
576         $query = new $queryClass($this);
577 
SYSTEMPATH\Database\BaseBuilder.php : 1512   —  CodeIgniter\Database\BaseConnection->query ( arguments )

1505             $sql = $this->compileSelect($this->countString . $this->db->protectIdentifiers('numrows'));
1506         }
1507 
1508         if ($this->testMode) {
1509             return $sql;
1510         }
1511 
1512         $result = $this->db->query($sql, $this->binds, false);
1513 
1514         if ($reset === true) {
1515             $this->resetSelect();
1516         } elseif (! isset($this->QBOrderBy)) {
1517             $this->QBOrderBy = $orderBy;
1518         }
1519 
SYSTEMPATH\Model.php : 509   —  CodeIgniter\Database\BaseBuilder->countAllResults ( arguments )

502         // When $reset === false, the $tempUseSoftDeletes will be
503         // dependant on $useSoftDeletes value because we don't
504         // want to add the same "where" condition for the second time
505         $this->tempUseSoftDeletes = $reset
506             ? $this->useSoftDeletes
507             : ($this->useSoftDeletes ? false : $this->useSoftDeletes);
508 
509         return $this->builder()->testMode($test)->countAllResults($reset);
510     }
511 
512     /**
513      * Provides a shared instance of the Query Builder.
514      *
515      * @throws ModelException
516      *
SYSTEMPATH\Model.php : 592   —  CodeIgniter\Model->countAllResults ()

585     protected function shouldUpdate($data): bool
586     {
587         // When useAutoIncrement feature is disabled check
588         // in the database if given record already exists
589         return parent::shouldUpdate($data)
590             && $this->useAutoIncrement
591                 ? true
592                 : $this->where($this->primaryKey, $this->getIdValue($data))->countAllResults() === 1;
593     }
594 
595     /**
596      * Inserts data into the database. If an object is provided,
597      * it will attempt to convert it to an array.
598      *
599      * @param array|object|null $data
SYSTEMPATH\BaseModel.php : 655   —  CodeIgniter\Model->shouldUpdate ( arguments )

648      */
649     public function save($data): bool
650     {
651         if (empty($data)) {
652             return true;
653         }
654 
655         if ($this->shouldUpdate($data)) {
656             $response = $this->update($this->getIdValue($data), $data);
657         } else {
658             $response = $this->insert($data, false);
659 
660             if ($response !== false) {
661                 $response = true;
662             }
APPPATH\Controllers\Blog.php : 50   —  CodeIgniter\BaseModel->save ( arguments )

43             'meta_title' => 'New Post ',
44             'title' => 'Create new post',
45         ];
46 
47         if($this->request->getMethod() == 'post')
48         {   
49             $model = new BlogModel();
50             $model->save($_POST);
51             // print_r($_POST);
52             // exit;
53         }
54         return  view('new_post',$data);
55 
56     }
57 
SYSTEMPATH\CodeIgniter.php : 802   —  App\Controllers\Blog->new ()

795     {
796         // If this is a console request then use the input segments as parameters
797         $params = defined('SPARKED') ? $this->request->getSegments() : $this->router->params(); // @phpstan-ignore-line
798 
799         if (method_exists($class, '_remap')) {
800             $output = $class->_remap($this->method, ...$params);
801         } else {
802             $output = $class->{$this->method}(...$params);
803         }
804 
805         $this->benchmark->stop('controller');
806 
807         return $output;
808     }
809 
SYSTEMPATH\CodeIgniter.php : 399   —  CodeIgniter\CodeIgniter->runController ( arguments )

392             if (! method_exists($controller, '_remap') && ! is_callable([$controller, $this->method], false)) {
393                 throw PageNotFoundException::forMethodNotFound($this->method);
394             }
395 
396             // Is there a "post_controller_constructor" event?
397             Events::trigger('post_controller_constructor');
398 
399             $returned = $this->runController($controller);
400         } else {
401             $this->benchmark->stop('controller_constructor');
402             $this->benchmark->stop('controller');
403         }
404 
405         // If $returned is a string, then the controller output something,
406         // probably a view, instead of echoing it directly. Send it along
SYSTEMPATH\CodeIgniter.php : 317   —  CodeIgniter\CodeIgniter->handleRequest ( arguments )

310             $this->response->pretend($this->useSafeOutput)->send();
311             $this->callExit(EXIT_SUCCESS);
312 
313             return;
314         }
315 
316         try {
317             return $this->handleRequest($routes, $cacheConfig, $returnResponse);
318         } catch (RedirectException $e) {
319             $logger = Services::logger();
320             $logger->info('REDIRECTED ROUTE at ' . $e->getMessage());
321 
322             // If the route is a 'redirect' route, it throws
323             // the exception with the $to as the message
324             $this->response->redirect(base_url($e->getMessage()), 'auto', $e->getCode());
FCPATH\index.php : 37   —  CodeIgniter\CodeIgniter->run ()

30 /*
31  *---------------------------------------------------------------
32  * LAUNCH THE APPLICATION
33  *---------------------------------------------------------------
34  * Now that everything is setup, it's time to actually fire
35  * up the engines and make this app do its thang.
36  */
37 $app->run();
38

**Comment by holynation** [comment]
I experienced this while I uploaded the project on a live server. Having confirmed that all requirements are meant. I just had to change my user access to another one, viola it works.

**Comment by informatico22** [comment]
> Many times replacing `localhost` with `127.0.0.1` will get your database working.

It Solve my problem... I just comment .env configuration database.. and fix it in database.php ..

**Comment by Hazzanawarafik** [comment]
> Many times replacing `localhost` with `127.0.0.1` will get your database working.

worked thanks you

**Comment by dhafinrh** [comment]
just wanna say thank you to everyone who gives their answer here
