### ISSUE TITLE
Bug: BaseBuilder's query is wrong

### ISSUE THREAD

**Issue by InsiteFX** [codeigniter4/CodeIgniter4#3659]
Newest CodeIgniter Developer version 4

BaseBuilder.php - The query method is being passed 3 parameters but the ConnectionInterface.php is only using 2 parameters.

Example:
system/Database/BaseBuilder.php
Line #1860
`: $this->db->query($this->compileSelect(), $this->binds, false);` <-- 3 parameters are being passed

system/Database/ConnectionInnterface.php

`public function query(string $sql, $binds = null);` <-- Only 2 signature parameters are defined

This is affecting every query method in BaseBuilder.php

 - OS: Windows 10 Pro x64
 - Web server Apache 2.4
 - PHP version 7.4.10

**Comment by michalsn** [comment]
Technically speaking it's not a bug since we still respect the contract in the `BaseConnection` class ([BaseConnection](https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Database/BaseConnection.php#L625), [ConnectionInterface](https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Database/ConnectionInterface.php#L162)). If the method's parameters have a default value then you don't have to specify them in the interface - they become an optional parameters and it gives you a lot of possibilities. 

In this case, I'm not really sure if we want to have all the parameters or are they missing by accident (probably?). However, the current implementation doesn't cause any malfunction.

From what I see this "pattern" occurs also in other database related interfaces (`PreparedQueryInterface`), so I will call @MGatner to discuss this more... should we keep the interface as it is or change it? I'm not sure if this may cause any problems for future drivers so there is a possiblility it was intended.

**Comment by InsiteFX** [comment]
No Problem, phpStorm flags like that. I guess it is just a warning from phpStorm.

**Comment by MGatner** [comment]
Probably PhpStorm hasn't scanned all the classes correctly. From PHP.net on interfaces:

> The class implementing the interface must use a method signatures which is compatible with LSP (Liskov Substitution Principle). Not doing so will result in a fatal error.

Basically it is okay for a class to build on an interface definition as long as it is not violating it.

@michalsn I think that some of these parameters were added later and thus not included in the interface. Whether that was by mistake or for backwards-compatibility I can't say, but for now I think we leave the less-restrictive interface. At some point (version 5? haha) I would like to see the whole database namespace get overhauled to be a) more loosely interoperative and b) less specific to SQL... that would likely be the time to redefine our interfaces or, more likely, to differentiate them.

**Comment by michalsn** [comment]
Yes, I'm not keen to make changes to the interfaces at this point either.
