### ISSUE TITLE
Bug: folder tests not found

### ISSUE THREAD

**Issue by totoprayogo1916** [codeigniter4/CodeIgniter4#3807]
**Describe the bug**
Follow the steps to install CI4 using composer: [this link](https://codeigniter4.github.io/userguide/installation/installing_composer.html#set-up)..

but in the framework folder, not found the tests folder.

**CodeIgniter 4 version: 4.0.4**

**Context**
 - OS: Windows 10
 - PHP version 7.4.11

**Comment by paulbalandan** [comment]
Are you using the `appstarter`?

**Comment by totoprayogo1916** [comment]
Appstarter is no problem. 
The problem when adding CodeIgniter4 to an existing project,

in the tutorial asked to copy some folder
but one folder is not available.
![Screenshot_2020-10-25-18-59-29-410_com android chrome](https://user-images.githubusercontent.com/2387514/97106533-d9fd0080-16f4-11eb-84f6-e2e892efa9e8.jpg)

**Comment by paulbalandan** [comment]
By chance, did you download `codeigniter4/framework` manually?

I see this as a documentation error because the deploy script does not include `tests` as folders to copy.

**Comment by paulbalandan** [comment]
OK. I checked this and `tests` is not there. This is not a bug though but is intended. The contents of `tests` is for the framework's test suite and you would never need that in your code that's why it is omitted.

You can, however, create your own `tests` folder at the same level of `app`, `public`, `writable`. Don't forget though to include the `_support` subfolder inside `tests` so that you can use the `SUPPORTPATH` constant in your testing.
