### ISSUE TITLE
Use hyphens in URL are not working 

### ISSUE THREAD

**Issue by potenzatk** [codeigniter4/CodeIgniter4#3923]
Hello,

We have created one method which working with an underscore but not working with hyphens.

Routes.php File code
$routes->add('/api/register-club', 'Api::registerClub');
$routes->add('/api/register_club', 'Api::registerClub');

http://prntscr.com/vpwshs
http://prntscr.com/vpwvfa

Thanks

**Comment by InsiteFX** [comment]
Translate URI Dashes
This option enables you to automatically replace dashes (‘-‘) with underscores in the controller and method URI segments, thus saving you additional route entries if you need to do that. This is required because the dash isn’t a valid class or method name character and would cause a fatal error if you try to use it:

`$routes->setTranslateURIDashes(false);`

**Comment by paulbalandan** [comment]
Closing as resolved.
