### ISSUE TITLE
I18n/L10n: auto update translations

### ISSUE THREAD

**Issue by WinterSilence** [codeigniter4/CodeIgniter4#4151]
Use something like [Github Translation Action](https://github.com/fabasoad/translation-action) or [Translate Shell](https://github.com/soimort/translate-shell) to translate new strings in config files.

Algorithm:
1. check lines in files `CodeIgniter4/system/Language/en/`
2. find untranslated lines in files  `CodeIgniter4/system/Language/{$language}/` (auto translation of new lines only)
3. auto translate lines and update files `CodeIgniter4/system/Language/{$language}/`

**Comment by sfadschm** [comment]
I think currently only `en` is desired to be shipped with the system folder. Translations are supposed to go into the `app/language` namespace and are maintained here:
https://github.com/codeigniter4/translations

Actually, we have a workflow there to check for new strings in the main repo `en` language, but those are then supposed to be manually updated by the maintainers.

Personally, I think in some cases automatic translation might work and could even be useful (e.g., standard error messages) but those should all already be included in the translations repo by now.

**Comment by WinterSilence** [comment]
@sfadschm yes, but github action must be add to this repo

**Comment by sfadschm** [comment]
Yes, if we want to implement automatic translation, we would need to add actions.
However, if we do so, messages will no longer be reliable in other languages. Hands down, automatic translation services sometimes significantly alter the meaning of messages, espacially when it comes to specialist terms and phrases. If something like that happens, the end users will get wrong or confusing (error) messages and put the app developers at trouble.
So I personally don't think that automatic translations should be implemented, but lets hear other opinions as well.

**Comment by WinterSilence** [comment]
@sfadschm 

>  (auto translation of new lines only)

these are temporary/initial stubs, devs can be replace them later

**Comment by sfadschm** [comment]
I honestly don't think thats reasonable. If any dev wants to translate one of the strings they can simply contribute to the `translations` repo. If they don't, language will fallback to english for this string, which will give a correct message.
However, lets hear what the maintainers think :-)

**Comment by paulbalandan** [comment]
Personally I do not like automated translations to the translations repo. As we have disclaimed there that we have no command in other language besides English, I think it is quite pretentious (or ironic?) to add automatically translated strings which are more often than not broken as to grammatical correctness or even the original meaning. For this reason we subscribe to the help of maintainers from the community to aid in a more "natural" translation rather than synthetic. Though I'll admit that the idea of maintainers was not efficient as originally planned because most are not active, I'll say human translators are relatively better. Besides, if the string has no equivalent translation then it will always fallback to `en` so there's nothing to worry about.

**Comment by michalsn** [comment]
I'm not a big fan of this idea. The quality of the translations would be rather poor. I definitely prefer to rely on people for this. Especially as Paul noted earlier - we have to be quite precise sometimes. With automatic translation, we wouldn't be able to check whether the translation made sense.

If the translation is out of date, then... oh well. We can only wait if someone needs it enough to add an update. Personally, I don't think it's a big deal.
