### ISSUE TITLE
Dev: 

### ISSUE THREAD

**Issue by ChibuezeAgwuDennis** [codeigniter4/CodeIgniter4#4233]
Should I said improvement to consider or a new feature to help on.
I am building an installer for my web app.
I try creating a database using the forge

```php
$this->forge->createDatabase('the_db_name', true);
```
first this demand me to connect to the database when I know I havng create the database
Please can it be possible to connect to the host without the database.
After the database creation it can be connect to.
I don't want to use php native code which only teach how to do this with mysql. that me is not going to work if my client db is not mysql.
Please can this be implement into the core code.
I have tried my best to see what I can do touch the source core code but not working.

I will be happy if this can be implement or is there any best way t do this with codeigniter

**Comment by xbotkaj** [comment]
Hi @ChibuezeAgwuDennis 

I assume you already configured database name in config and then you run forge. Because forge can connect to databse without creation it.

I believe what you need to do is set two database connections. One without any database specified and second with specified. When you run forge for the first time you want to use connection without databse specified, after that you will use default with datbase already specified... Something like this:

`	/**
	 * The default database connection.
	 *
	 * @var array
	 */
	public $default = [
		'DSN'      => '',
		'hostname' => 'localhost',
		'username' => 'root',
		'password' => '',
		'database' => 'my_database',
		'DBDriver' => 'MySQLi',
		'DBPrefix' => '',
		'pConnect' => false,
		'DBDebug'  => (ENVIRONMENT !== 'production'),
		'charset'  => 'utf8',
		'DBCollat' => 'utf8_general_ci',
		'swapPre'  => '',
		'encrypt'  => false,
		'compress' => false,
		'strictOn' => false,
		'failover' => [],
		'port'     => 3306,
	];

	/**
	 * The database connection without database specification.
	 *
	 * @var array
	 */
	public $db_root = [
		'DSN'      => '',
		'hostname' => 'localhost',
		'username' => 'root',
		'password' => '',
		'database' => '',
		'DBDriver' => 'MySQLi',
		'DBPrefix' => '',
		'pConnect' => false,
		'DBDebug'  => (ENVIRONMENT !== 'production'),
		'charset'  => 'utf8',
		'DBCollat' => 'utf8_general_ci',
		'swapPre'  => '',
		'encrypt'  => false,
		'compress' => false,
		'strictOn' => false,
		'failover' => [],
		'port'     => 3306,
	];`

Then I woud run in some controller database creation part and then run Migrations for default connection, since I am not sure if you can choose which database connection to use (but I can be wrong) :)

**Comment by MGatner** [comment]
Feature and support requests should be raised on the forums (https://forum.codeigniter.com/forum-28.html).

GitHub issues are for bug reports and already-discussed feature requests.
