### ISSUE TITLE
Bug: red line on model by setPrefix & prefixTable

### ISSUE THREAD

**Issue by totoprayogo1916** [codeigniter4/CodeIgniter4#4329]
**Describe the bug**
Found red line on Model (`setPrefix()` & `prefixTable()` )
![image](https://user-images.githubusercontent.com/2387514/108854108-0fb9e380-761a-11eb-866e-ab28d258e4df.png)

**CodeIgniter 4 version**
4.1.1

**Context**
 - OS: Windows 10
 - Web server, PHP Built in
 - PHP version 7.4.11

**Comment by MGatner** [comment]
It's because Model::$db is defined as a `ConnectionInterface` which only has a small subset of the actual methods in `BaseConnection`. Unfortunately we have a number of these discrepancies between base/abstract classes and typed interfaces. Since changing an interface is a breaking change it isn't an easy fix, but in the short term we could simply declare `Model::$db` as `ConnectionInterface|BaseConnection`. @samsonasik and @paulbalandan isn't that essentially how you fixed the similar issue with `ResponseInterface`?

**Comment by samsonasik** [comment]
Yes, on request use case, it was can't be changed in system, so change in `BaseController` instead, probably give a try apply `BaseConnection` to Base Model class ?
