### ISSUE TITLE
Bug: URI Routing Placeholders 

### ISSUE THREAD

**Issue by obipascal** [codeigniter4/CodeIgniter4#4421]
The URL Routing Placeholder does not capture the right values when defined
for example:
` $routes->get("/(:hash)", "Home::index/$1"); `
where the url is
` http://localhost/www/bitmoservice/public/#padoafa `

Will not grape the hash fragment of the url and also the 

` $routes->get("/(:any)", "Home::index/$1"); `
where the url is 
http://localhost/www/bitmoservice/public/path/to/resource

will not capture the: path/to/resource and return it as provided in the url.
` 
** Expected Results ** 
1. I was expecting to see the hash fragment passed to my controller and then i can retrieve it as argument.
2. secondly i was expecting the (:any) placeholder to return the whole fragment of the the url including the slashes as provided so i can determined what the user was trying to access. In the previous version of the app release this methods where working properly and in CI version 3 too.  Hope this will be identified and resolved soon.

CI Version 4.1.1

**Affected module(s)**
app\Config\Routes.php

**Context**
 - OS: [e.g. Windows 10 pro]
 - Web server [e.g. Apache 2.4.46]
 - PHP version [e.g. 7.4.59]

**Comment by MGatner** [comment]
`(:hash)` doesn't refer to the hashtag. I'm honestly not sure what that is supposed to do because it has the same placeholder regex as segment with no special handling:
```
	protected $placeholders = [
		'any'      => '.*',
		'segment'  => '[^/]+',
		'alphanum' => '[a-zA-Z0-9]+',
		'num'      => '[0-9]+',
		'alpha'    => '[a-zA-Z]+',
		'hash'     => '[^/]+',
	];
```

`(:any)` should indeed match "the rest of the URI" but my guess is that in your case it is failing because of the preceding slash with no other segment, but I'd have to look through the code to be sure. What do you get passed in as a parameter when it does match?

**Comment by MGatner** [comment]
@obipascal Any updates?

**Comment by obipascal** [comment]
Well i later used the  and it worked well with the functionality i wanted to achieve.
