### ISSUE TITLE
Bug: Ok The Model ERRORS came right back with the newest build again!

### ISSUE THREAD

**Issue by InsiteFX** [codeigniter4/CodeIgniter4#4491]
**Describe the bug**
My editor phpStorm 2020.3 is still flagging two ERRORS in the Model on `$this->db`

**CodeIgniter 4 version**
CodeIgniter 4 Develop branch newest download 10 minutes ago

**Affected module(s)**
system/Model

**Expected behavior, and steps to reproduce if appropriate**
Would expect to see no errors.
phpStorm support wants to see the database file. So I'll check with them and leave this open for now.

**Context**
 - OS: Windows 10 x64 build 20H2
 - Web server XAMPP Apache 2.4.46]
 - PHP version 8.0.3

**Comment by MGatner** [comment]
I think we will probably just end up merging the PR, even though this technically isn't our bug. Can you confirm that the PR fixes the issue? I.e. go make that one-line change in system and use it for a while to see if PHPStorm stops complaining?

**Comment by InsiteFX** [comment]
Adding the pr fix to the model has stopped the error for now. `protected $db`

**Comment by MGatner** [comment]
> protected $db

Do you mean `@property $db`? With final confirmation I will merge that PR.

**Comment by InsiteFX** [comment]
With `@property $db` it still errors the only way I can get it not to error is defining `protected $db;`

**Comment by InsiteFX** [comment]
Ok, PhpStorm's support just got back to me on this issue here it is what they told me.

[It's this one:](https://youtrack.jetbrains.com/issue/WI-21437)

Unfortunately, for now, you'll have to ignore the inspections hit, as protected members of mixin's are not supported currently. Please vote for the report, and sorry for the inconvenience!

**Comment by sfadschm** [comment]
That confirms this is only a PhpStorm issue right?

**Comment by InsiteFX** [comment]
That's right phpStorm doe's not handle mixin's.

**Comment by MGatner** [comment]
Thanks for the report. I would have to look at this more closely when not on mobile, but I *think* the issue is actually that they aren't giving `__get()` priority over the mixing. When you call `$model->db` what the runtime does is checks for the local public property then falls through to the accessor which checks the protected property, finds it, and stops there. What PHPStorm appears to do is check for the local property and then moves on to the `@mixin` for Builder. 

Actually now that I type this out, I don't know how they would fix this because the Model can't "mixin" its BaseModel so maybe we just need to fix this with annotations after all.

**Comment by paulbalandan** [comment]
This is not a framework issue, right? So, can this be closed?

**Comment by InsiteFX** [comment]
I don't know why that was still listed I told it to close it because I found out what was wrong.
Sorry for the trouble.
