### ISSUE TITLE
Release cycle 

### ISSUE THREAD

**Issue by iRedds** [codeigniter4/CodeIgniter4#4526]
I am writing this here because the chance to hear a response from the mainteners on the forum is zero.

The framework is released every six months when looking at the latest release dates.  I think that the release cycle needs to be revised.
In the issues section, users periodically write about problems that have already been resolved. 
What prevents you from doing a release once a month? Are you worried that the change log will be small?
I don't care about size. 

Okay. Make a monthly release with fixes only.
Although honestly I see no reason to wait half a year to add the feature.

Even in the instructions for contributors, it is recommended to use git-flow, which uses the hotfix branch.

**Comment by MGatner** [comment]
I'm on the forums a lot, and other maintainers show there too. The release poll was posted eight hours ago, midnight here. 

The team has already made some internal decisions around more frequent releases. I won't commit to a schedule here because the truth of it is we don't have enough help to make explicit dates happen. There is no "us" and "them" - anybody could pitch in for the work that needs to be done to prep a release.

We were going to do a release this past weekend but it is stalled by #4508 - once that is resolved we should have one out shortly.
