### ISSUE TITLE
Bug: Extra Headers on CURLRequest

### ISSUE THREAD

**Issue by jldorta** [codeigniter4/CodeIgniter4#4826]
**Describe the bug**
When you make a POST call to any controller on ServerA (RequestA) and then you use \Config\Services::curlrequest to make a "GET" request to a ServerB (RequestB), "MessageTrait.php" attach all the  RequestA Headers from the POST to the RequestB.  So the header "Content-Length" is sent to the ServerB.

**CodeIgniter 4 version**
CI 4.1.3

**Affected module(s)**
system/HTTP/CURLRequest.php
system/HTTP/MessageTrait.php

**Expected behavior, and steps to reproduce if appropriate**
The header "Content-Length" from the RequestA is sent to the ServerB as a Header.
Then ServerB wait for the body of the RequestB but since RequesB is "GET" the body is <EMPTY> that means the server make a GatewayTimeout.

**Context**
 - PHP version 7.4.20

**Comment by MGatner** [comment]
Values aren't reset between calls. If you want a "fresh start" then you should not use the shared service instance, get a new instance instead.

**Comment by jldorta** [comment]
I'm not using the same instance. I'm not even making a second request on the same server. Those are 2 different request in 2 diffenres servers

**Comment by paulbalandan** [comment]
Can you try using `single_service('curlrequest')` instead of `Services::curlrequest()`?

**Comment by jldorta** [comment]
Same issue, the only workaround that works is to set:
$_SERVER["HTTP_CONTENT_LENGTH"] = "";

 before making the request. It patches the problem but the bug remains there.

CURLRequest extends Request extends Message use MessageTrait::populateHeaders() 
For some reason populate all the current HEADERS to the new Request

**Comment by michalsn** [comment]
By default (as you noticed), the CURLRequest class copies all global headers if no custom headers are given. Please try adding custom headers:
```php
$client = Services::curlrequest(); 
$response = $client->request('GET', 'http://requestB', [
	'headers' => [
		'User-Agent' => 'hello/1.0'
	]
]);
```

**Comment by jldorta** [comment]
Exactly, but my question is why the system should copy by default all the headers including "HTTP_CONTENT_LENGTH"?

**Comment by michalsn** [comment]
I can only guess that most of the time it will be something desired since we will be mimic the "normal" request that the browser would make. I wouldn't call it a bug - this class was designed to work that way.

Maybe at some point, we should discuss if this should be a default behavior or not. Personally, I think that the current implementation works well for most people. We probably should document it better though.

**Comment by robentwist** [comment]
I have the same problem.  CI 4.1.3 as a REST server and a separate instance as a web site, calling the CI 4 REST server.

$client = CoreServices::curlrequest([
	'baseURI' => $this->app->api_url,
]);

This request times out:
$response = $client->request('GET', 'products/categories');

The bug is that CI inserts Content-Length: {} as a default header from the function $this->populateHeaders() as @jldorta states.  I can confirm this as well. This is called from protected function applyRequestHeaders on line 440 of vendor/codeigniter4/framework/system/HTTP/CURLRequest.php

This is fine for POST request, but SHOULD NOT be included for GET requests.  From the W3 recommendation:

14.13 Content-Length
The Content-Length entity-header field indicates the size of the entity-body, in decimal number of OCTETs, sent to the recipient or, **in the case of the HEAD method, the size of the entity-body that would have been sent** had the request been a GET.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.13

By writing over the headers as @michalsn says, it work since it removes the Content-Length header.  This should not be included in GET requests that are not HEAD only requests.

$response = $client->request('GET', 'products/categories', [
	'headers' => [
		'Authorization' => 'Bearer ' . $token,
	],
]);

**Comment by jldorta** [comment]
> I can only guess that most of the time it will be something desired since we will be mimic the "normal" request that the browser would make. I wouldn't call it a bug - this class was designed to work that way.
> 
> Maybe at some point, we should discuss if this should be a default behavior or not. Personally, I think that the current implementation works well for most people. We probably should document it better though.

I really doubt that the default behavior should be to pass all the headers from the current REQUEST to a new REQUEST. Anyway we need a way to avoid this because the method passes "ALL"  REQUEST headers

**Comment by kenjis** [comment]
I'm not sure we really need getting request headers form `$_SERVER`.
But sharing `Content-Length` between requests, we must say a bug.

I sent a PR to fix this. #5218

And the current behavior seems to be difficult to understand. If you have one header,
CURLRequest does not get request headers form `$_SERVER`.
And it is difficult to know whether you have headers or not.

**Comment by kenjis** [comment]
Now you can avoid this bug to set `Config\CURLRequest::$shareOptions` to `false`. 
See https://codeigniter4.github.io/CodeIgniter4/libraries/curlrequest.html#sharing-options

Or creating a new instance of `CURLRequest`.
