### ISSUE TITLE
Bug: View::include does not render 4options

### ISSUE THREAD

**Issue by JanZelenka** [codeigniter4/CodeIgniter4#4982]
Hi!
I'm trying to pass variables created in the main view into the included view. here is the call:

```
    $this->include(
            'StarMapObjects/StarSystem'
            , [
                    '$objStarSystem' => $objStarSystem
                    , '$objPresence' => $objMinorFaction->MinorFactionPresence[ $objStarSystem->name ]
                    ]
            );
```
But the included view doesn't recognize any of the passed $options keys as variables. When debugging the exception occurs on line 227 of View.php:

```
		$output = (function (): string {
			extract($this->tempData);
			ob_start();
			include $this->renderVars['file'];
			return ob_get_clean() ?: '';
		})();
```
Prior to this line I couldn't anything that would actually merge the $options into the $this->tempData array.

**CodeIgniter 4 version: 4.1.2**
**Affected module(s): CodeIgniter\View**

**Context**
 - OS: MacOS Big Sur 11.4
 - Web server: Apache 2.4.46
 - PHP version: 7.4.12

**Comment by paulbalandan** [comment]
Hi.

I think you are looking for the `setData` method instead of the options array. Options provide additional info that are shared across views for their own use. Since you are talking of `$this->tempData`, I assume you mean rendering the passed options as variables within views. That's not how options work. You should use the setData to persist data across views.

Another thing, if we'd allow options to be rendered, then passing the `cache` option would print the cache TTL in the views rather than processing it as additional info.
