### ISSUE TITLE
Image unlink in upload folder in not working using codeigniter4

### ISSUE THREAD

**Issue by yghodki** [codeigniter4/CodeIgniter4#4992]
// Controller code
public function deleteslider($id = null) {
        
        $image = $this->adminModel->sliderdelete($id);       
        $imagefile = 'public/uploads/admin/slider/' . $image;
        
        if (file_exists($imagefile) && !empty($image)) {
            unlink($imagefile);
            return redirect()->to('admin/slider')->with('fail', 'Somthing went wrong');
        } else {
            return redirect()->to('admin/slider')->with('success', 'Slider Image delete successfully');
        }
    }

// Model Code
 public function sliderdelete ($id) 
    {
        $builder = $this->db->table('slider');
        $builder->where('id', $id);
        $result = $builder->delete();
        
        if ($result > 0) {
            return true;
        } else {
            return false;
        }        
    }

**Comment by MGatner** [comment]
Support questions need to go to the forums - GitHub is for bugs and feature requests only. 

Incidentally, your `sliderdelete()` method returns a boolean, so `$image` will never be a file name and `$imagefile` will equal "public/uploads/admin/slider/". Since `file_exists()` passes for directories, that will always be true but `unlink()` will fail on directories.

**Comment by yghodki** [comment]
can you write suggested code

**Comment by MGatner** [comment]
I offer support for sponsorship (see my GitHub profile), or you can hire me through Upwork.

**Comment by yghodki** [comment]
ohhh! really..
why not i am correct that one.. my self
