### ISSUE TITLE
Bug: API routing not working, solution provided

### ISSUE THREAD

**Issue by askotx** [codeigniter4/CodeIgniter4#5043]
**Describe the bug**
I have a local machine working correctly a REST API, but when I upload my CI app to server, it shows home page index, but routes are not working, it only shows  "File not found" message.

**CodeIgniter 4 version**
4.1.3

**Affected module(s)**
Don't know.

**Expected behavior, and steps to reproduce if appropriate**
Routing should work as expected

**Context**
 - OS: [??]
 - Web server [Apache 2.4]
 - PHP version [7.3]

**Solution**
Like explained here:
https://forum.codeigniter.com/thread-74430-post-367770.html#pid367770
on file /public/.htacces line 34

```
RewriteRule ^([\s\S]*)$ index.php/$1 [L,NC,QSA]
```
Should be:
```
RewriteRule ^([\s\S]*)$ index.php?/$1 [L,NC,QSA]
```
Like this user said:
_I've found the solution !!!!
the error was in .htaccess file
i've just change the line : RewriteRule ^(.*)$ index.php/$1 [L]
by this one : RewriteRule ^(.*)$ index.php?/$1 [L]
just adding ? before the /$1_

I don't know what's the issue, nor the meaning of _?_, but that solved my problem too. This issue was from CI 4.0.0-rc.1

**Comment by paulbalandan** [comment]
This solution is not "inclusive" as it may work for you but will not work for others (including myself). This is an issue with different servers that a single htaccess file cannot solve. If the solution works for you, that's good. You may freely change it. For now, the htaccess version we have is the one that currently works with a "majority" of users. If this majority solution doesn't work for you, you can change your own. I hope you understand.

**Comment by askotx** [comment]
No, I don't understand. English  is not my native language. I read a lot of words from your response but no explanation was given. Anyway, this particular issue was no documented, if it works for someone, like me, great.

**Comment by paulbalandan** [comment]
Hmm.. okay.

The shipped rewriting rule in the htaccess file (`RewriteRule ^([\s\S]*)$ index.php/$1 [L,NC,QSA]`) works for most people. This one works because majority of servers they use support this syntax. But in your case since your server does not support this syntax you can freely change the htaccess file so that it will work in your case. No one is forbidding you or anyone else to change the htaccess file to work in their servers. If the solution works for you, as you have said, then it's great.

This is not documented because it is not a PHP or CI4 issue, but for servers which is beyond the scope of documentation.
