### ISSUE TITLE
Bug: $value is always null when validating single values with validation shortcut

### ISSUE THREAD

**Issue by KipchirchirIan** [codeigniter4/CodeIgniter4#5049]
**Description**
I am facing some issues when it comes to validating single values and I couldn't
tell where to place this, whether if it's under bug or support. Looking at the
documentation, to use the validation library, we need to load it as a service:

```php
$validation = \Config\Services::validation();
```
We can then validate  a single value against a set of rules(not sure about this) or a rule:
```php
$validation->check($value, 'required|number');
```
This seems to work fine and is expected to return `true` or `false`. Now, there is a shortcut 
just in case you don't want to load the `Validation` service and want to quickly validate 
something(within a controller):
```php
$this->validator->check($value, 'required|number');
```
I am assuming that they should work the same way and provide the same results
but I keep getting the error:
```
Call to a member function check() on null
```
even after providing a value and confirming that the value is actually there with
`dd($value)`.

**CodeIgniter 4 version**
CodeIgniter v4.1.3

**Affected module(s)**
`Validation`

**Expected behavior, and steps to reproduce if appropriate**
Inside a controller:
```php
/**
* Actual Behavior
*/
$value = 3;
$this->validator->check($value, 'required|is_natural_no_zero');
// Error: Call to a member function check() on null

$value = '';
$this->validator->check($value, 'required|is_natural_no_zero');
// Error: Call to a member function check() on null

$value = 'abc';
$this->validator->check($value, 'required|is_natural_no_zero');
// Error: Call to a member function check() on null

/**
* Expected Behavior
*/
$value = 3;
$this->validator->check($value, 'required|is_natural_no_zero'); // returns TRUE

$value = '';
$this->validator->check($value, 'required|is_natural_no_zero'); // returns FALSE

$value = 'abc';
$this->validator->check($value, 'required|is_natural_no_zero'); // returns FALSE
```

**Context**
 - OS: Ubuntu 18.04.5
 - Web server: Apache 2.4.43]
 - PHP version: 7.4.8

**Comment by iRedds** [comment]
```Call to a member function check() on null``` 
this means that the $this->validation property is undefined.
By default, the property is determined when the $this->validate() method is called in the controller.

**Comment by paulbalandan** [comment]
@iRedds is correct.

The property is filled with the validation object when you used the `$this->validate()` method of the controller. https://github.com/codeigniter4/CodeIgniter4/blob/4ab9d66b530ec798f2b06a551a2cab8797161f5d/system/Controller.php#L139

In your case, you are accessing `$this->validator` outside the scope of the method so the property is not initialized with the needed validation service. Since you are doing validations, I suggest to use the `$this->validate()` method instead as it does the same thing as what you want to achieve.

If you, however, would still want to access `$this->validator` in other methods of the controller (or in your controller perhaps), you can send a PR moving the instantiation to the constructor instead. Thanks.

**Comment by KipchirchirIan** [comment]
Thank you! I think I get the picture now. I should have researched more on this.
