### ISSUE TITLE
docs: `Codeigniter\Model::getInsertID()` is not described

### ISSUE THREAD

**Issue by dgvirtual** [codeigniter4/CodeIgniter4#5377]
Method getInsertID of the Codeigniter model is not documented; it would be useful to do that... 

`$this->workModel->insert($fields); 
$newID = $this->workModel->getInsertID()`

**Comment by rmullaney77** [comment]
Presume because one would not be expected to call that method directly 🤔

See `$db->insertID()` at https://codeigniter.com/user_guide/database/helpers.html

`grep -ir "insertID(" *`
`system/Test/Mock/MockConnection.php:    public function insertID(): int`
`system/Database/SQLite3/Connection.php:    public function insertID(): int`
`system/Database/SQLSRV/Connection.php:    public function insertID(): int`
`system/Database/MySQLi/Connection.php:    public function insertID(): int`
`system/Database/BaseConnection.php:    abstract public function insertID();`
`system/Database/Postgre/Connection.php:    public function insertID()`
`system/BaseModel.php:    public function getInsertID()`
`system/Model.php:            $this->insertID = ! $this->useAutoIncrement ? $data[$this->primaryKey] : $this->db->insertID();`

**Comment by dgvirtual** [comment]
OK, thanks, I was not aware of `$db->insertID()` , which, I have found out, could be used with the Codeigniter model as well directly, just like the getInsertID(); 

I do not know if it is a feature or a bug, but `insertID()` and `getInsertID()` can give very different results, if a model has a filter defined that runs after each db insert and executes it's own insert. 

In my case, I have implemented an action log that takes the data that has been inserted and does another insert into a log table of the database. So, I have a model CallsModel defined for table **calls* and a filter defined in it: 

`    protected $afterInsert = ['log_db_insert'];
    protected function log_db_insert(array $darray)
    {
        if ($darray['result'] == 1) {
            $zLogModel = model('ZLogModel');
            $data = [
                'user_id'    => $_SESSION['user_id'],
                'table'      => 'calls',
                'action_id'  => 'clC', 
                'row_id'     => $darray['id'],
                'content'    => (!empty($darray['data'])) ? json_encode($darray['data'], JSON_UNESCAPED_UNICODE) : null,
            ];
            $zLogModel->insert($data);
        }
        return $darray;
    }`

So, in my controller, I run an insert command

`$this->callsModel->insert($fields)`

and then I need to get the new id from the table **calls**. if I run:

`$insert_id = $this->callsModel->getInsertID()` 

I do get the ID that I need. 

However, if I run 

`$insert_id = $this->callsModel->insertID()` 

I get the id of the *filter operation - the new ID from the log table*.

I doubt this is the intended behavior. 

Ah, in case that is significant, my CI version is v4.1.7, and I am using SQLITE db.

**Comment by kenjis** [comment]
If you use the Model, you should use the Model's method.

> I do not know if it is a feature or a bug, but insertID() and getInsertID() can give very different results,

Not a feature and not a bug.
It may be design flaw that "could be used with the Codeigniter model directly".
