### ISSUE TITLE
Thanks for screwing up the best framework there was for php

### ISSUE THREAD

**Issue by vitolike** [codeigniter4/CodeIgniter4#5615]
Thanks for screwing up the best framework there was for php, CI4 looks like a bad copy of Laravel, full of bugs, I liked CI3 better and what I can do I'll make it live, thanks team for the crap

**Comment by iRedds** [comment]
CI3 was obsolete at the time of its first release.
Yes, CI4 has problems, but they are solved and it is many times better both in language support and in the implementation of design patterns than CI3.
I don't see anything wrong with using good solutions from other frameworks.

You could contribute to improving the framework, but at the moment, I do not see any PR or Issue from you in the CI4 or CI3 repositories.

**Comment by kenjis** [comment]
@vitolike 
It seems you have something to say, but unfortunately I don't get what you really want to say
and what you want. Because I don't know what you experienced.

Would you like to say that you don't like Laravel?
Would you like to declare your contribution to CI3?

Anyway, we use this GitHub Issues as a bug tracker.
If you find unreported bugs, you can file the bugs.
You can find reported bugs: https://github.com/codeigniter4/CodeIgniter4/issues?q=is%3Aopen+label%3Abug+sort%3Aupdated-desc

If you want community support, navigate to https://forum.codeigniter.com/forum-30.html
