### ISSUE TITLE
Bug: current_url() doesn't include query parameters

### ISSUE THREAD

**Issue by Mauricevb** [codeigniter4/CodeIgniter4#6111]
### PHP Version

7.4

### CodeIgniter4 Version

4.2.0

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### What happened?

The helper function [current_url()](https://codeigniter4.github.io/CodeIgniter4/helpers/url_helper.html?highlight=url) returns the current URL without query parameters, but `(string) current_url(true)` does. This is not clear in the documentation and I'm not sure if this is expected behaviour. 

```php
// URL in browser: http://domain.com?key=value

echo current_url() // http://domain.com

echo (string) current_url(true) // http://domain.com?key=value
```

### Steps to Reproduce

Use  [current_url()](https://codeigniter4.github.io/CodeIgniter4/helpers/url_helper.html?highlight=url) function on with an URL  that contains parameters.

### Expected Output

I'm not sure what is the expected behaviour. The documentation is not really clear on this.

**Comment by kenjis** [comment]
The user guide says `current_url() = site_url(uri_string())`.
So `current_url()` does not contain query parameters.

> `current_url([$returnObject = false[, $request = null]])`
> Calling this function is the same as doing this:
> `site_url(uri_string());`
https://codeigniter4.github.io/CodeIgniter4/helpers/url_helper.html#current_url

> `uri_string([$relative = false])`
> Returns the path part of the current URL.
https://codeigniter4.github.io/CodeIgniter4/helpers/url_helper.html#uri_string

On the other hand, `current_url(true)` returns a URI object.
The URI class represents a URI, and when it is cast to string, it contains  query parameters.

So these are expected behavior.

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
