### ISSUE TITLE
BUG: I'm in the version  4.1.9 That works properly, but when I update to 4.2.1 the SQL Server 2017 

### ISSUE THREAD

**Issue by DASE1312** [codeigniter4/CodeIgniter4#6165]
### PHP Version

7.4

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

sqlserver 2017

### What happened?

When I update to v 4.2.1.  An error pop-up 
"CodeIgniter\Database\Exceptions\DatabaseException #8
Unable to connect to the database.
Main connection [sqlsrv]: Proveedor de TCP: Tiempo de espera de la operación de espera agotado."
I understand that the error is due to internet connection, but the device where i'm working is connected directly to the ethernet of the company. 

### Steps to Reproduce

I want to a login like i used to connect in the version 4.1.9 (i make a backup) , but the error pop-up

### Expected Output

Validate the user to if there are register to the database

**Comment by iRedds** [comment]
Try commenting out the port in the connection settings and connect to the database. Write if the behavior will change.

**Comment by DASE1312** [comment]
Indeed, my friend, it was resolved by commenting on the port to which this behaviour is due, could you explain it to me?

**Comment by iRedds** [comment]
In 4.2.0, a fix was added to a bug due to which a port was not used when creating a connection to the database. That is, the connection always went through the default port. And if the server listened to a non-standard port, then the connection did not occur.

I want to note that all CI tests related to working with the database, including MSSQL, pass. Therefore, the reason for this behavior is currently unclear.
