### ISSUE TITLE
php 8.2 session error err_empty_response

### ISSUE THREAD

**Issue by kimdoyeonsa** [codeigniter4/CodeIgniter4#7121]
php 8.2 
apache
linux

$this->session = \Config\Services::session(); 

err_empty_response

 
![2023-01-15_124504](https://user-images.githubusercontent.com/48858134/212521914-db7b3fda-efb8-427c-9b4a-91252dd4fc8a.jpg)

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.

If you think your issue is a bug, please choose "Bug report".
https://github.com/codeigniter4/CodeIgniter4/issues/new/choose
