### ISSUE TITLE
Bug: error in fetching error message after redirect process

### ISSUE THREAD

**Issue by ahmadinzero** [codeigniter4/CodeIgniter4#7330]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.2

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli

### What happened?

when the validation process failed I redirected it back to the form page, but when I retrieved the error message using the `getErrors()` method it returned an empty array, after I traced the problem was in the `getErrors()` method in `CodeIgniter/Validation/Validation.php`

### Steps to Reproduce

```php
// in file User.php
  public function index() {
    $session = \Config\Services::session();
    $validation = \Config\Services::validation();
    d($validation->getErrors());
    return view('form');
  }

  public function save() {
    $validation = \Config\Services::validation();
    $validation->setRules([
      'name' => 'required'
    ]);
    if ($validation->withRequest($this->request)->run() == false) {
      //redirect back to form page
      //dd($validation);
      return redirect()->back()->withInput();
    }
  }
  
  
```

### Expected Output

what I'm expecting is an array containing the error messages
for example 
```php
['The name field is required.']
```

**Comment by kenjis** [comment]
This is expected. Because HTTP is stateless.
In the second request, you don't validate anything, so there is no error.

If you depend on the bug in the previous versions, Please read:
https://codeigniter4.github.io/CodeIgniter4/installation/upgrade_430.html#redirect-withinput-and-validation-errors

**Comment by ahmadinzero** [comment]
@kenjis sorry, I've tried to fix it, please see my pull request [7331](https://github.com/codeigniter4/CodeIgniter4/pull/7331)

**Comment by kenjis** [comment]
Please use new Form helpers, [validation_errors()](https://codeigniter4.github.io/CodeIgniter4/helpers/form_helper.html#validation_errors), [validation_list_errors()](https://codeigniter4.github.io/CodeIgniter4/helpers/form_helper.html#validation_list_errors) and [validation_show_error()](https://codeigniter4.github.io/CodeIgniter4/helpers/form_helper.html#validation_show_error) to display Validation Errors, instead of the Validation object.

**Comment by kenjis** [comment]
@ahmadinzero just a question. Are you a beginner for PHP web programming?
Why did you think the Validation object should return the validation error in a previous request?

**Comment by ahmadinzero** [comment]
@kenjis Yes, I'm still a beginner in PHP programming.
what I mean is not before the request, but after the redirect process.  maybe I made a mistake when I made the issue, sorry because my English is not good

**Comment by kenjis** [comment]
@ahmadinzero Thank you for reply! No problem.
I asked you for improving our documentation. See #7332

When you use *redirect*, CI4 sends a HTTP response that tells to redirect to the URI.
And when the browser get the response, it sends another request to the URI.
There are two requests when you use redirect.
And PHP shares nothing between requests (except Session).
So the Validation object in the second request is not the same object in the first request,
and the new Validation object in the second request has no error because no validation runs.

**Comment by ahmadinzero** [comment]
@kenjis okay thanks for taking the time to help me
