### ISSUE TITLE
Making defined routes and auto routing work together

### ISSUE THREAD

**Issue by atiabjobayer** [codeigniter4/CodeIgniter4#7861]
The documentation has a note saying *For security reasons, if a controller is used in the defined routes, Auto Routing (Improved) does not route to the controller.*

Can anyone please explain why is making both work together a security issue? In my opinion it would be a very user friendly feature.

**Comment by kenjis** [comment]
If you really want to use defined routes and auto routing together, you could use [Auto Routing (Legacy)](https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html#auto-routing-legacy).

But, for example, see [this tutorial](https://www.binaryboxtuts.com/php-tutorials/codeigniter-4-json-web-tokenjwt-authentication/). If you build the tutorial app with Auto Routing (Legacy), an attacker could get list of users without token.

**Comment by atiabjobayer** [comment]
No I can understand the issues in Legacy Auto Routing. That's why I moved to the improved one.

Now let's say I have 10 methods in a controller, and for only one of them, I want to use a defined route. Now is there any way(probably regex route or something) I can make the other methods keep working as they usually do?

**Comment by kenjis** [comment]
> I have 10 methods in a controller, and for only one of them, I want to use a defined route.

How do I know which method is used for the defined route when I look at the controller code?
And why do you need to use defined route only for the method?

In order to prohibit such complicated configurations, auto routing improved does not work for the controller if even one method is registered to a defined route. This is because allowing complicated configurations makes it easier for configuration errors to occur. Keep it simple.

If you use defined route, you must define all routes for the controller.
If you use auto routing improved, you cannot use defined route at all for the controller.
This is much simpler and easier to understand than the behavior of stopping auto routing only for the method registered in a defined route.

My recommendation is one (action) method in one controller. If you follow this practice, you never have 10 methods in a controller.

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
