### ISSUE TITLE
Bug: CSRF not regenerate when redirect another page

### ISSUE THREAD

**Issue by ariefcahya** [codeigniter4/CodeIgniter4#8163]
### PHP Version

8.2

### CodeIgniter4 Version

4.3.7

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

maria db

### What happened?

I have a little confusion with CSRF (Cross-Site Request Forgery). I've set "security.regenerate" to "true," and the CSRF token is successfully regenerated every time it's used. However, when I add a redirect to another page, the token is not regenerated (it remains the same as before the form submission).

### Steps to Reproduce

Case 1:
In the Login controller, which contains a view for login, when I submit to the checkLogin controller, the CSRF token is successfully regenerated.

Case 2:
In the Login controller, which contains a view for login, when I submit to the checkLogin controller, and then successfully log in, and redirect to the dashboard, the CSRF token is not regenerated.

Case 3:
In the Login controller, which contains a view for login, when I submit to the checkLogin controller and login fails, and I'm redirected back to the login page, the CSRF token is not regenerated.

### Expected Output

still generates tokens even though it redirects to another page

**Comment by kenjis** [comment]
If you use Cookie based CSRF protection (CI4 default), do you call `withCookie()`?
See https://codeigniter4.github.io/CodeIgniter4/outgoing/response.html#redirect-back

Also, if you use Session, you should use Session based CSRF protection.
See https://codeigniter4.github.io/CodeIgniter4/libraries/security.html#csrf-protection-methods
Because Cookie based CSRF protection cannot protect Same-site attack.
See https://github.com/codeigniter4/shield/security/advisories/GHSA-5hm8-vh6r-2cjq

**Comment by ariefcahya** [comment]
it worked, thanks for your help @kenjis 
I think it would be complicated if you needed to add withCookie to every redirect. I will just use session.

**Comment by kenjis** [comment]
I sent PR #8164

**Comment by kenjis** [comment]
And sent #8166
